// https://github.com/toptal/haste-server/blob/master/static/application.js#L167-L174
// Popular extension map
const exts = {
  rb: 'ruby',
  py: 'python',
  pl: 'perl',
  php: 'php',
  scala: 'scala',
  go: 'go',
  xml: 'xml',
  html: 'xml',
  htm: 'xml',
  css: 'css',
  js: 'javascript',
  json: 'json',
  vbs: 'vbscript',
  lua: 'lua',
  pas: 'delphi',
  java: 'java',
  cpp: 'cpp',
  cc: 'cpp',
  m: 'objectivec',
  vala: 'vala',
  sql: 'sql',
  sm: 'smalltalk',
  lisp: 'lisp',
  ini: 'ini',
  diff: 'diff',
  bash: 'bash',
  sh: 'bash',
  tex: 'tex',
  erl: 'erlang',
  hs: 'haskell',
  md: 'markdown',
  txt: '',
  coffee: 'coffee',
  swift: 'swift',
};

export default exts;