// https://github.com/toptal/haste-server/blob/master/static/application.js#L167-L174
// Popular extension map
const exts = {
  md: 'Markdown',
  css: 'CSS',
  js: 'JavaScript',
  json: 'JSON',
  html: 'HTML',
  ts: 'TypeScript',
  java: 'Java',
  py: 'Python',
  rb: 'Ruby',
  sh: 'Shell',
  php: 'PHP',
  pl: 'Perl',
  sql: 'SQL',
  xml: 'XML',
  yml: 'YAML',
  yaml: 'YAML',
  c: 'C',
  cpp: 'C++',
  cs: 'C#',
  go: 'Go',
  h: 'C/C++ Header',
  txt: 'Text',
  dockerfile: 'Dockerfile',
  toml: 'TOML',
  ini: 'INI',
  bat: 'Batch File',
  tex: 'TeX',
  r: 'R',
  lua: 'Lua',
  ps1: 'PowerShell',
  rst: 'reStructuredText',
  rs: 'Rust',
  swift: 'Swift',
  scss: 'SCSS',
  less: 'LESS',
  scala: 'Scala',
  kotlin: 'Kotlin',
  vb: 'Visual Basic',
  vim: 'Vim Script',
};

export default exts;
