allowBuilds:
  '@parcel/watcher': true
  argon2: true
  esbuild: true
  sharp: true
ignoredBuiltDependencies:
  - unrs-resolver
onlyBuiltDependencies:
  - '@parcel/watcher'
  - argon2
  - esbuild
  - sharp
