
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models.js"
import { type PrismaClient } from "./class.js"

export type * from '../models.js'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Validator
 */
export const validator = runtime.Public.validator

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
 * Metrics
 */
export type Metrics = runtime.Metrics
export type Metric<T> = runtime.Metric<T>
export type MetricHistogram = runtime.MetricHistogram
export type MetricHistogramBucket = runtime.MetricHistogramBucket

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 6.13.0
 * Query Engine version: 361e86d0ea4987e9f53a565309b3eed797a6bcbd
 */
export const prismaVersion: PrismaVersion = {
  client: "6.13.0",
  engine: "361e86d0ea4987e9f53a565309b3eed797a6bcbd"
}

/**
 * Utility Types
 */

export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue

export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}

/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull

type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Zipline: 'Zipline',
  User: 'User',
  Export: 'Export',
  UserQuota: 'UserQuota',
  UserPasskey: 'UserPasskey',
  OAuthProvider: 'OAuthProvider',
  File: 'File',
  Thumbnail: 'Thumbnail',
  Folder: 'Folder',
  IncompleteFile: 'IncompleteFile',
  Tag: 'Tag',
  Url: 'Url',
  Metric: 'Metric',
  Invite: 'Invite'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<ClientOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], ClientOptions extends { omit: infer OmitOptions } ? OmitOptions : {}>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "zipline" | "user" | "export" | "userQuota" | "userPasskey" | "oAuthProvider" | "file" | "thumbnail" | "folder" | "incompleteFile" | "tag" | "url" | "metric" | "invite"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Zipline: {
      payload: Prisma.$ZiplinePayload<ExtArgs>
      fields: Prisma.ZiplineFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ZiplineFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ZiplinePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ZiplineFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ZiplinePayload>
        }
        findFirst: {
          args: Prisma.ZiplineFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ZiplinePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ZiplineFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ZiplinePayload>
        }
        findMany: {
          args: Prisma.ZiplineFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ZiplinePayload>[]
        }
        create: {
          args: Prisma.ZiplineCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ZiplinePayload>
        }
        createMany: {
          args: Prisma.ZiplineCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ZiplineCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ZiplinePayload>[]
        }
        delete: {
          args: Prisma.ZiplineDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ZiplinePayload>
        }
        update: {
          args: Prisma.ZiplineUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ZiplinePayload>
        }
        deleteMany: {
          args: Prisma.ZiplineDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ZiplineUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ZiplineUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ZiplinePayload>[]
        }
        upsert: {
          args: Prisma.ZiplineUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ZiplinePayload>
        }
        aggregate: {
          args: Prisma.ZiplineAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateZipline>
        }
        groupBy: {
          args: Prisma.ZiplineGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ZiplineGroupByOutputType>[]
        }
        count: {
          args: Prisma.ZiplineCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ZiplineCountAggregateOutputType> | number
        }
      }
    }
    User: {
      payload: Prisma.$UserPayload<ExtArgs>
      fields: Prisma.UserFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findFirst: {
          args: Prisma.UserFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findMany: {
          args: Prisma.UserFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        create: {
          args: Prisma.UserCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        createMany: {
          args: Prisma.UserCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        delete: {
          args: Prisma.UserDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        update: {
          args: Prisma.UserUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        deleteMany: {
          args: Prisma.UserDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        upsert: {
          args: Prisma.UserUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        aggregate: {
          args: Prisma.UserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUser>
        }
        groupBy: {
          args: Prisma.UserGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserCountAggregateOutputType> | number
        }
      }
    }
    Export: {
      payload: Prisma.$ExportPayload<ExtArgs>
      fields: Prisma.ExportFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ExportFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExportPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ExportFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExportPayload>
        }
        findFirst: {
          args: Prisma.ExportFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExportPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ExportFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExportPayload>
        }
        findMany: {
          args: Prisma.ExportFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExportPayload>[]
        }
        create: {
          args: Prisma.ExportCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExportPayload>
        }
        createMany: {
          args: Prisma.ExportCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ExportCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExportPayload>[]
        }
        delete: {
          args: Prisma.ExportDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExportPayload>
        }
        update: {
          args: Prisma.ExportUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExportPayload>
        }
        deleteMany: {
          args: Prisma.ExportDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ExportUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ExportUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExportPayload>[]
        }
        upsert: {
          args: Prisma.ExportUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExportPayload>
        }
        aggregate: {
          args: Prisma.ExportAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateExport>
        }
        groupBy: {
          args: Prisma.ExportGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ExportGroupByOutputType>[]
        }
        count: {
          args: Prisma.ExportCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ExportCountAggregateOutputType> | number
        }
      }
    }
    UserQuota: {
      payload: Prisma.$UserQuotaPayload<ExtArgs>
      fields: Prisma.UserQuotaFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserQuotaFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserQuotaPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserQuotaFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserQuotaPayload>
        }
        findFirst: {
          args: Prisma.UserQuotaFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserQuotaPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserQuotaFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserQuotaPayload>
        }
        findMany: {
          args: Prisma.UserQuotaFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserQuotaPayload>[]
        }
        create: {
          args: Prisma.UserQuotaCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserQuotaPayload>
        }
        createMany: {
          args: Prisma.UserQuotaCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserQuotaCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserQuotaPayload>[]
        }
        delete: {
          args: Prisma.UserQuotaDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserQuotaPayload>
        }
        update: {
          args: Prisma.UserQuotaUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserQuotaPayload>
        }
        deleteMany: {
          args: Prisma.UserQuotaDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserQuotaUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserQuotaUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserQuotaPayload>[]
        }
        upsert: {
          args: Prisma.UserQuotaUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserQuotaPayload>
        }
        aggregate: {
          args: Prisma.UserQuotaAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUserQuota>
        }
        groupBy: {
          args: Prisma.UserQuotaGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserQuotaGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserQuotaCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserQuotaCountAggregateOutputType> | number
        }
      }
    }
    UserPasskey: {
      payload: Prisma.$UserPasskeyPayload<ExtArgs>
      fields: Prisma.UserPasskeyFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserPasskeyFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPasskeyPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserPasskeyFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPasskeyPayload>
        }
        findFirst: {
          args: Prisma.UserPasskeyFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPasskeyPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserPasskeyFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPasskeyPayload>
        }
        findMany: {
          args: Prisma.UserPasskeyFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPasskeyPayload>[]
        }
        create: {
          args: Prisma.UserPasskeyCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPasskeyPayload>
        }
        createMany: {
          args: Prisma.UserPasskeyCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserPasskeyCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPasskeyPayload>[]
        }
        delete: {
          args: Prisma.UserPasskeyDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPasskeyPayload>
        }
        update: {
          args: Prisma.UserPasskeyUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPasskeyPayload>
        }
        deleteMany: {
          args: Prisma.UserPasskeyDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserPasskeyUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserPasskeyUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPasskeyPayload>[]
        }
        upsert: {
          args: Prisma.UserPasskeyUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPasskeyPayload>
        }
        aggregate: {
          args: Prisma.UserPasskeyAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUserPasskey>
        }
        groupBy: {
          args: Prisma.UserPasskeyGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserPasskeyGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserPasskeyCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserPasskeyCountAggregateOutputType> | number
        }
      }
    }
    OAuthProvider: {
      payload: Prisma.$OAuthProviderPayload<ExtArgs>
      fields: Prisma.OAuthProviderFieldRefs
      operations: {
        findUnique: {
          args: Prisma.OAuthProviderFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OAuthProviderPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.OAuthProviderFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OAuthProviderPayload>
        }
        findFirst: {
          args: Prisma.OAuthProviderFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OAuthProviderPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.OAuthProviderFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OAuthProviderPayload>
        }
        findMany: {
          args: Prisma.OAuthProviderFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OAuthProviderPayload>[]
        }
        create: {
          args: Prisma.OAuthProviderCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OAuthProviderPayload>
        }
        createMany: {
          args: Prisma.OAuthProviderCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.OAuthProviderCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OAuthProviderPayload>[]
        }
        delete: {
          args: Prisma.OAuthProviderDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OAuthProviderPayload>
        }
        update: {
          args: Prisma.OAuthProviderUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OAuthProviderPayload>
        }
        deleteMany: {
          args: Prisma.OAuthProviderDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.OAuthProviderUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.OAuthProviderUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OAuthProviderPayload>[]
        }
        upsert: {
          args: Prisma.OAuthProviderUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OAuthProviderPayload>
        }
        aggregate: {
          args: Prisma.OAuthProviderAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateOAuthProvider>
        }
        groupBy: {
          args: Prisma.OAuthProviderGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.OAuthProviderGroupByOutputType>[]
        }
        count: {
          args: Prisma.OAuthProviderCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.OAuthProviderCountAggregateOutputType> | number
        }
      }
    }
    File: {
      payload: Prisma.$FilePayload<ExtArgs>
      fields: Prisma.FileFieldRefs
      operations: {
        findUnique: {
          args: Prisma.FileFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.FileFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilePayload>
        }
        findFirst: {
          args: Prisma.FileFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.FileFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilePayload>
        }
        findMany: {
          args: Prisma.FileFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilePayload>[]
        }
        create: {
          args: Prisma.FileCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilePayload>
        }
        createMany: {
          args: Prisma.FileCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.FileCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilePayload>[]
        }
        delete: {
          args: Prisma.FileDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilePayload>
        }
        update: {
          args: Prisma.FileUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilePayload>
        }
        deleteMany: {
          args: Prisma.FileDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.FileUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.FileUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilePayload>[]
        }
        upsert: {
          args: Prisma.FileUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilePayload>
        }
        aggregate: {
          args: Prisma.FileAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateFile>
        }
        groupBy: {
          args: Prisma.FileGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FileGroupByOutputType>[]
        }
        count: {
          args: Prisma.FileCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FileCountAggregateOutputType> | number
        }
      }
    }
    Thumbnail: {
      payload: Prisma.$ThumbnailPayload<ExtArgs>
      fields: Prisma.ThumbnailFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ThumbnailFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ThumbnailPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ThumbnailFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ThumbnailPayload>
        }
        findFirst: {
          args: Prisma.ThumbnailFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ThumbnailPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ThumbnailFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ThumbnailPayload>
        }
        findMany: {
          args: Prisma.ThumbnailFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ThumbnailPayload>[]
        }
        create: {
          args: Prisma.ThumbnailCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ThumbnailPayload>
        }
        createMany: {
          args: Prisma.ThumbnailCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ThumbnailCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ThumbnailPayload>[]
        }
        delete: {
          args: Prisma.ThumbnailDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ThumbnailPayload>
        }
        update: {
          args: Prisma.ThumbnailUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ThumbnailPayload>
        }
        deleteMany: {
          args: Prisma.ThumbnailDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ThumbnailUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ThumbnailUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ThumbnailPayload>[]
        }
        upsert: {
          args: Prisma.ThumbnailUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ThumbnailPayload>
        }
        aggregate: {
          args: Prisma.ThumbnailAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateThumbnail>
        }
        groupBy: {
          args: Prisma.ThumbnailGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ThumbnailGroupByOutputType>[]
        }
        count: {
          args: Prisma.ThumbnailCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ThumbnailCountAggregateOutputType> | number
        }
      }
    }
    Folder: {
      payload: Prisma.$FolderPayload<ExtArgs>
      fields: Prisma.FolderFieldRefs
      operations: {
        findUnique: {
          args: Prisma.FolderFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolderPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.FolderFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolderPayload>
        }
        findFirst: {
          args: Prisma.FolderFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolderPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.FolderFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolderPayload>
        }
        findMany: {
          args: Prisma.FolderFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolderPayload>[]
        }
        create: {
          args: Prisma.FolderCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolderPayload>
        }
        createMany: {
          args: Prisma.FolderCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.FolderCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolderPayload>[]
        }
        delete: {
          args: Prisma.FolderDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolderPayload>
        }
        update: {
          args: Prisma.FolderUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolderPayload>
        }
        deleteMany: {
          args: Prisma.FolderDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.FolderUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.FolderUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolderPayload>[]
        }
        upsert: {
          args: Prisma.FolderUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolderPayload>
        }
        aggregate: {
          args: Prisma.FolderAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateFolder>
        }
        groupBy: {
          args: Prisma.FolderGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FolderGroupByOutputType>[]
        }
        count: {
          args: Prisma.FolderCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FolderCountAggregateOutputType> | number
        }
      }
    }
    IncompleteFile: {
      payload: Prisma.$IncompleteFilePayload<ExtArgs>
      fields: Prisma.IncompleteFileFieldRefs
      operations: {
        findUnique: {
          args: Prisma.IncompleteFileFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncompleteFilePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.IncompleteFileFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncompleteFilePayload>
        }
        findFirst: {
          args: Prisma.IncompleteFileFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncompleteFilePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.IncompleteFileFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncompleteFilePayload>
        }
        findMany: {
          args: Prisma.IncompleteFileFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncompleteFilePayload>[]
        }
        create: {
          args: Prisma.IncompleteFileCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncompleteFilePayload>
        }
        createMany: {
          args: Prisma.IncompleteFileCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.IncompleteFileCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncompleteFilePayload>[]
        }
        delete: {
          args: Prisma.IncompleteFileDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncompleteFilePayload>
        }
        update: {
          args: Prisma.IncompleteFileUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncompleteFilePayload>
        }
        deleteMany: {
          args: Prisma.IncompleteFileDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.IncompleteFileUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.IncompleteFileUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncompleteFilePayload>[]
        }
        upsert: {
          args: Prisma.IncompleteFileUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncompleteFilePayload>
        }
        aggregate: {
          args: Prisma.IncompleteFileAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateIncompleteFile>
        }
        groupBy: {
          args: Prisma.IncompleteFileGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.IncompleteFileGroupByOutputType>[]
        }
        count: {
          args: Prisma.IncompleteFileCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.IncompleteFileCountAggregateOutputType> | number
        }
      }
    }
    Tag: {
      payload: Prisma.$TagPayload<ExtArgs>
      fields: Prisma.TagFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TagFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TagFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload>
        }
        findFirst: {
          args: Prisma.TagFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TagFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload>
        }
        findMany: {
          args: Prisma.TagFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload>[]
        }
        create: {
          args: Prisma.TagCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload>
        }
        createMany: {
          args: Prisma.TagCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TagCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload>[]
        }
        delete: {
          args: Prisma.TagDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload>
        }
        update: {
          args: Prisma.TagUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload>
        }
        deleteMany: {
          args: Prisma.TagDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TagUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TagUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload>[]
        }
        upsert: {
          args: Prisma.TagUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload>
        }
        aggregate: {
          args: Prisma.TagAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTag>
        }
        groupBy: {
          args: Prisma.TagGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TagGroupByOutputType>[]
        }
        count: {
          args: Prisma.TagCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TagCountAggregateOutputType> | number
        }
      }
    }
    Url: {
      payload: Prisma.$UrlPayload<ExtArgs>
      fields: Prisma.UrlFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UrlFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UrlFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload>
        }
        findFirst: {
          args: Prisma.UrlFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UrlFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload>
        }
        findMany: {
          args: Prisma.UrlFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload>[]
        }
        create: {
          args: Prisma.UrlCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload>
        }
        createMany: {
          args: Prisma.UrlCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UrlCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload>[]
        }
        delete: {
          args: Prisma.UrlDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload>
        }
        update: {
          args: Prisma.UrlUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload>
        }
        deleteMany: {
          args: Prisma.UrlDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UrlUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UrlUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload>[]
        }
        upsert: {
          args: Prisma.UrlUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload>
        }
        aggregate: {
          args: Prisma.UrlAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUrl>
        }
        groupBy: {
          args: Prisma.UrlGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UrlGroupByOutputType>[]
        }
        count: {
          args: Prisma.UrlCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UrlCountAggregateOutputType> | number
        }
      }
    }
    Metric: {
      payload: Prisma.$MetricPayload<ExtArgs>
      fields: Prisma.MetricFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MetricFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MetricFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricPayload>
        }
        findFirst: {
          args: Prisma.MetricFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MetricFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricPayload>
        }
        findMany: {
          args: Prisma.MetricFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricPayload>[]
        }
        create: {
          args: Prisma.MetricCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricPayload>
        }
        createMany: {
          args: Prisma.MetricCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.MetricCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricPayload>[]
        }
        delete: {
          args: Prisma.MetricDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricPayload>
        }
        update: {
          args: Prisma.MetricUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricPayload>
        }
        deleteMany: {
          args: Prisma.MetricDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MetricUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.MetricUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricPayload>[]
        }
        upsert: {
          args: Prisma.MetricUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricPayload>
        }
        aggregate: {
          args: Prisma.MetricAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMetric>
        }
        groupBy: {
          args: Prisma.MetricGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MetricGroupByOutputType>[]
        }
        count: {
          args: Prisma.MetricCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MetricCountAggregateOutputType> | number
        }
      }
    }
    Invite: {
      payload: Prisma.$InvitePayload<ExtArgs>
      fields: Prisma.InviteFieldRefs
      operations: {
        findUnique: {
          args: Prisma.InviteFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvitePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.InviteFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvitePayload>
        }
        findFirst: {
          args: Prisma.InviteFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvitePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.InviteFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvitePayload>
        }
        findMany: {
          args: Prisma.InviteFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvitePayload>[]
        }
        create: {
          args: Prisma.InviteCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvitePayload>
        }
        createMany: {
          args: Prisma.InviteCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.InviteCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvitePayload>[]
        }
        delete: {
          args: Prisma.InviteDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvitePayload>
        }
        update: {
          args: Prisma.InviteUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvitePayload>
        }
        deleteMany: {
          args: Prisma.InviteDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.InviteUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.InviteUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvitePayload>[]
        }
        upsert: {
          args: Prisma.InviteUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvitePayload>
        }
        aggregate: {
          args: Prisma.InviteAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateInvite>
        }
        groupBy: {
          args: Prisma.InviteGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.InviteGroupByOutputType>[]
        }
        count: {
          args: Prisma.InviteCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.InviteCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ZiplineScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  firstSetup: 'firstSetup',
  coreReturnHttpsUrls: 'coreReturnHttpsUrls',
  coreDefaultDomain: 'coreDefaultDomain',
  coreTempDirectory: 'coreTempDirectory',
  chunksEnabled: 'chunksEnabled',
  chunksMax: 'chunksMax',
  chunksSize: 'chunksSize',
  tasksDeleteInterval: 'tasksDeleteInterval',
  tasksClearInvitesInterval: 'tasksClearInvitesInterval',
  tasksMaxViewsInterval: 'tasksMaxViewsInterval',
  tasksThumbnailsInterval: 'tasksThumbnailsInterval',
  tasksMetricsInterval: 'tasksMetricsInterval',
  filesRoute: 'filesRoute',
  filesLength: 'filesLength',
  filesDefaultFormat: 'filesDefaultFormat',
  filesDisabledExtensions: 'filesDisabledExtensions',
  filesMaxFileSize: 'filesMaxFileSize',
  filesDefaultExpiration: 'filesDefaultExpiration',
  filesAssumeMimetypes: 'filesAssumeMimetypes',
  filesDefaultDateFormat: 'filesDefaultDateFormat',
  filesRemoveGpsMetadata: 'filesRemoveGpsMetadata',
  filesRandomWordsNumAdjectives: 'filesRandomWordsNumAdjectives',
  filesRandomWordsSeparator: 'filesRandomWordsSeparator',
  filesDefaultCompressionFormat: 'filesDefaultCompressionFormat',
  urlsRoute: 'urlsRoute',
  urlsLength: 'urlsLength',
  featuresImageCompression: 'featuresImageCompression',
  featuresRobotsTxt: 'featuresRobotsTxt',
  featuresHealthcheck: 'featuresHealthcheck',
  featuresUserRegistration: 'featuresUserRegistration',
  featuresOauthRegistration: 'featuresOauthRegistration',
  featuresDeleteOnMaxViews: 'featuresDeleteOnMaxViews',
  featuresThumbnailsEnabled: 'featuresThumbnailsEnabled',
  featuresThumbnailsNumberThreads: 'featuresThumbnailsNumberThreads',
  featuresThumbnailsFormat: 'featuresThumbnailsFormat',
  featuresMetricsEnabled: 'featuresMetricsEnabled',
  featuresMetricsAdminOnly: 'featuresMetricsAdminOnly',
  featuresMetricsShowUserSpecific: 'featuresMetricsShowUserSpecific',
  featuresVersionChecking: 'featuresVersionChecking',
  featuresVersionAPI: 'featuresVersionAPI',
  invitesEnabled: 'invitesEnabled',
  invitesLength: 'invitesLength',
  websiteTitle: 'websiteTitle',
  websiteTitleLogo: 'websiteTitleLogo',
  websiteExternalLinks: 'websiteExternalLinks',
  websiteLoginBackground: 'websiteLoginBackground',
  websiteLoginBackgroundBlur: 'websiteLoginBackgroundBlur',
  websiteDefaultAvatar: 'websiteDefaultAvatar',
  websiteTos: 'websiteTos',
  websiteThemeDefault: 'websiteThemeDefault',
  websiteThemeDark: 'websiteThemeDark',
  websiteThemeLight: 'websiteThemeLight',
  oauthBypassLocalLogin: 'oauthBypassLocalLogin',
  oauthLoginOnly: 'oauthLoginOnly',
  oauthDiscordClientId: 'oauthDiscordClientId',
  oauthDiscordClientSecret: 'oauthDiscordClientSecret',
  oauthDiscordRedirectUri: 'oauthDiscordRedirectUri',
  oauthDiscordAllowedIds: 'oauthDiscordAllowedIds',
  oauthDiscordDeniedIds: 'oauthDiscordDeniedIds',
  oauthGoogleClientId: 'oauthGoogleClientId',
  oauthGoogleClientSecret: 'oauthGoogleClientSecret',
  oauthGoogleRedirectUri: 'oauthGoogleRedirectUri',
  oauthGithubClientId: 'oauthGithubClientId',
  oauthGithubClientSecret: 'oauthGithubClientSecret',
  oauthGithubRedirectUri: 'oauthGithubRedirectUri',
  oauthOidcClientId: 'oauthOidcClientId',
  oauthOidcClientSecret: 'oauthOidcClientSecret',
  oauthOidcAuthorizeUrl: 'oauthOidcAuthorizeUrl',
  oauthOidcTokenUrl: 'oauthOidcTokenUrl',
  oauthOidcUserinfoUrl: 'oauthOidcUserinfoUrl',
  oauthOidcRedirectUri: 'oauthOidcRedirectUri',
  mfaTotpEnabled: 'mfaTotpEnabled',
  mfaTotpIssuer: 'mfaTotpIssuer',
  mfaPasskeys: 'mfaPasskeys',
  ratelimitEnabled: 'ratelimitEnabled',
  ratelimitMax: 'ratelimitMax',
  ratelimitWindow: 'ratelimitWindow',
  ratelimitAdminBypass: 'ratelimitAdminBypass',
  ratelimitAllowList: 'ratelimitAllowList',
  httpWebhookOnUpload: 'httpWebhookOnUpload',
  httpWebhookOnShorten: 'httpWebhookOnShorten',
  discordWebhookUrl: 'discordWebhookUrl',
  discordUsername: 'discordUsername',
  discordAvatarUrl: 'discordAvatarUrl',
  discordOnUploadWebhookUrl: 'discordOnUploadWebhookUrl',
  discordOnUploadUsername: 'discordOnUploadUsername',
  discordOnUploadAvatarUrl: 'discordOnUploadAvatarUrl',
  discordOnUploadContent: 'discordOnUploadContent',
  discordOnUploadEmbed: 'discordOnUploadEmbed',
  discordOnShortenWebhookUrl: 'discordOnShortenWebhookUrl',
  discordOnShortenUsername: 'discordOnShortenUsername',
  discordOnShortenAvatarUrl: 'discordOnShortenAvatarUrl',
  discordOnShortenContent: 'discordOnShortenContent',
  discordOnShortenEmbed: 'discordOnShortenEmbed',
  pwaEnabled: 'pwaEnabled',
  pwaTitle: 'pwaTitle',
  pwaShortName: 'pwaShortName',
  pwaDescription: 'pwaDescription',
  pwaThemeColor: 'pwaThemeColor',
  pwaBackgroundColor: 'pwaBackgroundColor',
  domains: 'domains'
} as const

export type ZiplineScalarFieldEnum = (typeof ZiplineScalarFieldEnum)[keyof typeof ZiplineScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  username: 'username',
  password: 'password',
  avatar: 'avatar',
  token: 'token',
  role: 'role',
  view: 'view',
  totpSecret: 'totpSecret',
  sessions: 'sessions'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const ExportScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  completed: 'completed',
  path: 'path',
  files: 'files',
  size: 'size',
  userId: 'userId'
} as const

export type ExportScalarFieldEnum = (typeof ExportScalarFieldEnum)[keyof typeof ExportScalarFieldEnum]


export const UserQuotaScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  filesQuota: 'filesQuota',
  maxBytes: 'maxBytes',
  maxFiles: 'maxFiles',
  maxUrls: 'maxUrls',
  userId: 'userId'
} as const

export type UserQuotaScalarFieldEnum = (typeof UserQuotaScalarFieldEnum)[keyof typeof UserQuotaScalarFieldEnum]


export const UserPasskeyScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  lastUsed: 'lastUsed',
  name: 'name',
  reg: 'reg',
  userId: 'userId'
} as const

export type UserPasskeyScalarFieldEnum = (typeof UserPasskeyScalarFieldEnum)[keyof typeof UserPasskeyScalarFieldEnum]


export const OAuthProviderScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  provider: 'provider',
  username: 'username',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  oauthId: 'oauthId'
} as const

export type OAuthProviderScalarFieldEnum = (typeof OAuthProviderScalarFieldEnum)[keyof typeof OAuthProviderScalarFieldEnum]


export const FileScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletesAt: 'deletesAt',
  name: 'name',
  originalName: 'originalName',
  size: 'size',
  type: 'type',
  views: 'views',
  maxViews: 'maxViews',
  favorite: 'favorite',
  password: 'password',
  userId: 'userId',
  folderId: 'folderId'
} as const

export type FileScalarFieldEnum = (typeof FileScalarFieldEnum)[keyof typeof FileScalarFieldEnum]


export const ThumbnailScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  path: 'path',
  fileId: 'fileId'
} as const

export type ThumbnailScalarFieldEnum = (typeof ThumbnailScalarFieldEnum)[keyof typeof ThumbnailScalarFieldEnum]


export const FolderScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  public: 'public',
  allowUploads: 'allowUploads',
  userId: 'userId'
} as const

export type FolderScalarFieldEnum = (typeof FolderScalarFieldEnum)[keyof typeof FolderScalarFieldEnum]


export const IncompleteFileScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  status: 'status',
  chunksTotal: 'chunksTotal',
  chunksComplete: 'chunksComplete',
  metadata: 'metadata',
  userId: 'userId'
} as const

export type IncompleteFileScalarFieldEnum = (typeof IncompleteFileScalarFieldEnum)[keyof typeof IncompleteFileScalarFieldEnum]


export const TagScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  color: 'color',
  userId: 'userId'
} as const

export type TagScalarFieldEnum = (typeof TagScalarFieldEnum)[keyof typeof TagScalarFieldEnum]


export const UrlScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  code: 'code',
  vanity: 'vanity',
  destination: 'destination',
  views: 'views',
  maxViews: 'maxViews',
  password: 'password',
  enabled: 'enabled',
  userId: 'userId'
} as const

export type UrlScalarFieldEnum = (typeof UrlScalarFieldEnum)[keyof typeof UrlScalarFieldEnum]


export const MetricScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  data: 'data'
} as const

export type MetricScalarFieldEnum = (typeof MetricScalarFieldEnum)[keyof typeof MetricScalarFieldEnum]


export const InviteScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  expiresAt: 'expiresAt',
  code: 'code',
  uses: 'uses',
  maxUses: 'maxUses',
  inviterId: 'inviterId'
} as const

export type InviteScalarFieldEnum = (typeof InviteScalarFieldEnum)[keyof typeof InviteScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'Json'
 */
export type JsonFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Json'>
    


/**
 * Reference to a field of type 'QueryMode'
 */
export type EnumQueryModeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'QueryMode'>
    


/**
 * Reference to a field of type 'Role'
 */
export type EnumRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Role'>
    


/**
 * Reference to a field of type 'Role[]'
 */
export type ListEnumRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Role[]'>
    


/**
 * Reference to a field of type 'UserFilesQuota'
 */
export type EnumUserFilesQuotaFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'UserFilesQuota'>
    


/**
 * Reference to a field of type 'UserFilesQuota[]'
 */
export type ListEnumUserFilesQuotaFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'UserFilesQuota[]'>
    


/**
 * Reference to a field of type 'OAuthProviderType'
 */
export type EnumOAuthProviderTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'OAuthProviderType'>
    


/**
 * Reference to a field of type 'OAuthProviderType[]'
 */
export type ListEnumOAuthProviderTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'OAuthProviderType[]'>
    


/**
 * Reference to a field of type 'BigInt'
 */
export type BigIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BigInt'>
    


/**
 * Reference to a field of type 'BigInt[]'
 */
export type ListBigIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BigInt[]'>
    


/**
 * Reference to a field of type 'IncompleteFileStatus'
 */
export type EnumIncompleteFileStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'IncompleteFileStatus'>
    


/**
 * Reference to a field of type 'IncompleteFileStatus[]'
 */
export type ListEnumIncompleteFileStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'IncompleteFileStatus[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}


export type Datasource = {
  url?: string
}
export type Datasources = {
  db?: Datasource
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export interface PrismaClientOptions {
  /**
   * Overwrites the datasource url from your schema.prisma file
   */
  datasources?: Datasources
  /**
   * Overwrites the datasource url from your schema.prisma file
   */
  datasourceUrl?: string
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/logging#the-log-option).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-planetscale`
   */
  adapter?: runtime.SqlDriverAdapterFactory | null
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
}
export type GlobalOmitConfig = {
  zipline?: Prisma.ZiplineOmit
  user?: Prisma.UserOmit
  export?: Prisma.ExportOmit
  userQuota?: Prisma.UserQuotaOmit
  userPasskey?: Prisma.UserPasskeyOmit
  oAuthProvider?: Prisma.OAuthProviderOmit
  file?: Prisma.FileOmit
  thumbnail?: Prisma.ThumbnailOmit
  folder?: Prisma.FolderOmit
  incompleteFile?: Prisma.IncompleteFileOmit
  tag?: Prisma.TagOmit
  url?: Prisma.UrlOmit
  metric?: Prisma.MetricOmit
  invite?: Prisma.InviteOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * These options are being passed into the middleware as "params"
 */
export type MiddlewareParams = {
  model?: ModelName
  action: PrismaAction
  args: any
  dataPath: string[]
  runInTransaction: boolean
}

/**
 * The `T` type makes sure, that the `return proceed` is not forgotten in the middleware implementation
 */
export type Middleware<T = any> = (
  params: MiddlewareParams,
  next: (params: MiddlewareParams) => runtime.Types.Utils.JsPromise<T>,
) => runtime.Types.Utils.JsPromise<T>

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

