name: Suggestion
description: Suggest a feature to be added
title: 'Suggestion: '
labels: ['suggestion']
body:
  - type: textarea
    id: suggest
    attributes:
      label: Suggestion
      description: Be as descriptive as possible!
      placeholder: What do you want in Zipline?
      value: A suggestion
