
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.js"
import * as $Class from "./internal/class.js"
import * as Prisma from "./internal/prismaNamespace.js"

export * as $Enums from './enums.js'
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Ziplines
 * const ziplines = await prisma.zipline.findMany()
 * ```
 * 
 * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client).
 */
export const PrismaClient = $Class.getPrismaClientClass(__dirname)
export type PrismaClient<ClientOptions extends Prisma.PrismaClientOptions = Prisma.PrismaClientOptions, Log = $Class.LogOptions<ClientOptions>, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<ClientOptions, Log, ExtArgs>
export { Prisma }



/**
 * Model Zipline
 * 
 */
export type Zipline = Prisma.ZiplineModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Export
 * 
 */
export type Export = Prisma.ExportModel
/**
 * Model UserQuota
 * 
 */
export type UserQuota = Prisma.UserQuotaModel
/**
 * Model UserPasskey
 * 
 */
export type UserPasskey = Prisma.UserPasskeyModel
/**
 * Model OAuthProvider
 * 
 */
export type OAuthProvider = Prisma.OAuthProviderModel
/**
 * Model File
 * 
 */
export type File = Prisma.FileModel
/**
 * Model Thumbnail
 * 
 */
export type Thumbnail = Prisma.ThumbnailModel
/**
 * Model Folder
 * 
 */
export type Folder = Prisma.FolderModel
/**
 * Model IncompleteFile
 * 
 */
export type IncompleteFile = Prisma.IncompleteFileModel
/**
 * Model Tag
 * 
 */
export type Tag = Prisma.TagModel
/**
 * Model Url
 * 
 */
export type Url = Prisma.UrlModel
/**
 * Model Metric
 * 
 */
export type Metric = Prisma.MetricModel
/**
 * Model Invite
 * 
 */
export type Invite = Prisma.InviteModel

export type UserFilesQuota = $Enums.UserFilesQuota
export const UserFilesQuota = $Enums.UserFilesQuota

export type Role = $Enums.Role
export const Role = $Enums.Role

export type OAuthProviderType = $Enums.OAuthProviderType
export const OAuthProviderType = $Enums.OAuthProviderType

export type IncompleteFileStatus = $Enums.IncompleteFileStatus
export const IncompleteFileStatus = $Enums.IncompleteFileStatus
