
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/
export const UserFilesQuota = {
  BY_BYTES: 'BY_BYTES',
  BY_FILES: 'BY_FILES'
} as const

export type UserFilesQuota = (typeof UserFilesQuota)[keyof typeof UserFilesQuota]


export const Role = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  SUPERADMIN: 'SUPERADMIN'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const OAuthProviderType = {
  DISCORD: 'DISCORD',
  GOOGLE: 'GOOGLE',
  GITHUB: 'GITHUB',
  OIDC: 'OIDC'
} as const

export type OAuthProviderType = (typeof OAuthProviderType)[keyof typeof OAuthProviderType]


export const IncompleteFileStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETE: 'COMPLETE',
  FAILED: 'FAILED'
} as const

export type IncompleteFileStatus = (typeof IncompleteFileStatus)[keyof typeof IncompleteFileStatus]
