version: '3.8'
services:
  app:
    image: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-18
    volumes:
      - ..:/workspace:cached
    network_mode: service:db
    command: sleep infinity
    user: zipline
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    