version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../:/zipline:cached
      - uploads:/zipline/uploads
      - node_modules:/zipline/node_modules
    command: sleep infinity
    links:
      - db:postgres
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  uploads:
  node_modules: