
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `Export` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Export
 * 
 */
export type ExportModel = runtime.Types.Result.DefaultSelection<Prisma.$ExportPayload>

export type AggregateExport = {
  _count: ExportCountAggregateOutputType | null
  _avg: ExportAvgAggregateOutputType | null
  _sum: ExportSumAggregateOutputType | null
  _min: ExportMinAggregateOutputType | null
  _max: ExportMaxAggregateOutputType | null
}

export type ExportAvgAggregateOutputType = {
  files: number | null
}

export type ExportSumAggregateOutputType = {
  files: number | null
}

export type ExportMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  completed: boolean | null
  path: string | null
  files: number | null
  size: string | null
  userId: string | null
}

export type ExportMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  completed: boolean | null
  path: string | null
  files: number | null
  size: string | null
  userId: string | null
}

export type ExportCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  completed: number
  path: number
  files: number
  size: number
  userId: number
  _all: number
}


export type ExportAvgAggregateInputType = {
  files?: true
}

export type ExportSumAggregateInputType = {
  files?: true
}

export type ExportMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  completed?: true
  path?: true
  files?: true
  size?: true
  userId?: true
}

export type ExportMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  completed?: true
  path?: true
  files?: true
  size?: true
  userId?: true
}

export type ExportCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  completed?: true
  path?: true
  files?: true
  size?: true
  userId?: true
  _all?: true
}

export type ExportAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Export to aggregate.
   */
  where?: Prisma.ExportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Exports to fetch.
   */
  orderBy?: Prisma.ExportOrderByWithRelationInput | Prisma.ExportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ExportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Exports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Exports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Exports
  **/
  _count?: true | ExportCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ExportAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ExportSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ExportMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ExportMaxAggregateInputType
}

export type GetExportAggregateType<T extends ExportAggregateArgs> = {
      [P in keyof T & keyof AggregateExport]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateExport[P]>
    : Prisma.GetScalarType<T[P], AggregateExport[P]>
}




export type ExportGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExportWhereInput
  orderBy?: Prisma.ExportOrderByWithAggregationInput | Prisma.ExportOrderByWithAggregationInput[]
  by: Prisma.ExportScalarFieldEnum[] | Prisma.ExportScalarFieldEnum
  having?: Prisma.ExportScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ExportCountAggregateInputType | true
  _avg?: ExportAvgAggregateInputType
  _sum?: ExportSumAggregateInputType
  _min?: ExportMinAggregateInputType
  _max?: ExportMaxAggregateInputType
}

export type ExportGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  completed: boolean
  path: string
  files: number
  size: string
  userId: string
  _count: ExportCountAggregateOutputType | null
  _avg: ExportAvgAggregateOutputType | null
  _sum: ExportSumAggregateOutputType | null
  _min: ExportMinAggregateOutputType | null
  _max: ExportMaxAggregateOutputType | null
}

type GetExportGroupByPayload<T extends ExportGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ExportGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ExportGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ExportGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ExportGroupByOutputType[P]>
      }
    >
  >



export type ExportWhereInput = {
  AND?: Prisma.ExportWhereInput | Prisma.ExportWhereInput[]
  OR?: Prisma.ExportWhereInput[]
  NOT?: Prisma.ExportWhereInput | Prisma.ExportWhereInput[]
  id?: Prisma.StringFilter<"Export"> | string
  createdAt?: Prisma.DateTimeFilter<"Export"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Export"> | Date | string
  completed?: Prisma.BoolFilter<"Export"> | boolean
  path?: Prisma.StringFilter<"Export"> | string
  files?: Prisma.IntFilter<"Export"> | number
  size?: Prisma.StringFilter<"Export"> | string
  userId?: Prisma.StringFilter<"Export"> | string
  User?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type ExportOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  completed?: Prisma.SortOrder
  path?: Prisma.SortOrder
  files?: Prisma.SortOrder
  size?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  User?: Prisma.UserOrderByWithRelationInput
}

export type ExportWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ExportWhereInput | Prisma.ExportWhereInput[]
  OR?: Prisma.ExportWhereInput[]
  NOT?: Prisma.ExportWhereInput | Prisma.ExportWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"Export"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Export"> | Date | string
  completed?: Prisma.BoolFilter<"Export"> | boolean
  path?: Prisma.StringFilter<"Export"> | string
  files?: Prisma.IntFilter<"Export"> | number
  size?: Prisma.StringFilter<"Export"> | string
  userId?: Prisma.StringFilter<"Export"> | string
  User?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type ExportOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  completed?: Prisma.SortOrder
  path?: Prisma.SortOrder
  files?: Prisma.SortOrder
  size?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  _count?: Prisma.ExportCountOrderByAggregateInput
  _avg?: Prisma.ExportAvgOrderByAggregateInput
  _max?: Prisma.ExportMaxOrderByAggregateInput
  _min?: Prisma.ExportMinOrderByAggregateInput
  _sum?: Prisma.ExportSumOrderByAggregateInput
}

export type ExportScalarWhereWithAggregatesInput = {
  AND?: Prisma.ExportScalarWhereWithAggregatesInput | Prisma.ExportScalarWhereWithAggregatesInput[]
  OR?: Prisma.ExportScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ExportScalarWhereWithAggregatesInput | Prisma.ExportScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Export"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Export"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Export"> | Date | string
  completed?: Prisma.BoolWithAggregatesFilter<"Export"> | boolean
  path?: Prisma.StringWithAggregatesFilter<"Export"> | string
  files?: Prisma.IntWithAggregatesFilter<"Export"> | number
  size?: Prisma.StringWithAggregatesFilter<"Export"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Export"> | string
}

export type ExportCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  completed?: boolean
  path: string
  files: number
  size: string
  User: Prisma.UserCreateNestedOneWithoutExportsInput
}

export type ExportUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  completed?: boolean
  path: string
  files: number
  size: string
  userId: string
}

export type ExportUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  path?: Prisma.StringFieldUpdateOperationsInput | string
  files?: Prisma.IntFieldUpdateOperationsInput | number
  size?: Prisma.StringFieldUpdateOperationsInput | string
  User?: Prisma.UserUpdateOneRequiredWithoutExportsNestedInput
}

export type ExportUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  path?: Prisma.StringFieldUpdateOperationsInput | string
  files?: Prisma.IntFieldUpdateOperationsInput | number
  size?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ExportCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  completed?: boolean
  path: string
  files: number
  size: string
  userId: string
}

export type ExportUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  path?: Prisma.StringFieldUpdateOperationsInput | string
  files?: Prisma.IntFieldUpdateOperationsInput | number
  size?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ExportUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  path?: Prisma.StringFieldUpdateOperationsInput | string
  files?: Prisma.IntFieldUpdateOperationsInput | number
  size?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ExportListRelationFilter = {
  every?: Prisma.ExportWhereInput
  some?: Prisma.ExportWhereInput
  none?: Prisma.ExportWhereInput
}

export type ExportOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ExportCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  completed?: Prisma.SortOrder
  path?: Prisma.SortOrder
  files?: Prisma.SortOrder
  size?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type ExportAvgOrderByAggregateInput = {
  files?: Prisma.SortOrder
}

export type ExportMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  completed?: Prisma.SortOrder
  path?: Prisma.SortOrder
  files?: Prisma.SortOrder
  size?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type ExportMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  completed?: Prisma.SortOrder
  path?: Prisma.SortOrder
  files?: Prisma.SortOrder
  size?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type ExportSumOrderByAggregateInput = {
  files?: Prisma.SortOrder
}

export type ExportCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ExportCreateWithoutUserInput, Prisma.ExportUncheckedCreateWithoutUserInput> | Prisma.ExportCreateWithoutUserInput[] | Prisma.ExportUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ExportCreateOrConnectWithoutUserInput | Prisma.ExportCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ExportCreateManyUserInputEnvelope
  connect?: Prisma.ExportWhereUniqueInput | Prisma.ExportWhereUniqueInput[]
}

export type ExportUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ExportCreateWithoutUserInput, Prisma.ExportUncheckedCreateWithoutUserInput> | Prisma.ExportCreateWithoutUserInput[] | Prisma.ExportUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ExportCreateOrConnectWithoutUserInput | Prisma.ExportCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ExportCreateManyUserInputEnvelope
  connect?: Prisma.ExportWhereUniqueInput | Prisma.ExportWhereUniqueInput[]
}

export type ExportUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ExportCreateWithoutUserInput, Prisma.ExportUncheckedCreateWithoutUserInput> | Prisma.ExportCreateWithoutUserInput[] | Prisma.ExportUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ExportCreateOrConnectWithoutUserInput | Prisma.ExportCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ExportUpsertWithWhereUniqueWithoutUserInput | Prisma.ExportUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ExportCreateManyUserInputEnvelope
  set?: Prisma.ExportWhereUniqueInput | Prisma.ExportWhereUniqueInput[]
  disconnect?: Prisma.ExportWhereUniqueInput | Prisma.ExportWhereUniqueInput[]
  delete?: Prisma.ExportWhereUniqueInput | Prisma.ExportWhereUniqueInput[]
  connect?: Prisma.ExportWhereUniqueInput | Prisma.ExportWhereUniqueInput[]
  update?: Prisma.ExportUpdateWithWhereUniqueWithoutUserInput | Prisma.ExportUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ExportUpdateManyWithWhereWithoutUserInput | Prisma.ExportUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ExportScalarWhereInput | Prisma.ExportScalarWhereInput[]
}

export type ExportUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ExportCreateWithoutUserInput, Prisma.ExportUncheckedCreateWithoutUserInput> | Prisma.ExportCreateWithoutUserInput[] | Prisma.ExportUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ExportCreateOrConnectWithoutUserInput | Prisma.ExportCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ExportUpsertWithWhereUniqueWithoutUserInput | Prisma.ExportUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ExportCreateManyUserInputEnvelope
  set?: Prisma.ExportWhereUniqueInput | Prisma.ExportWhereUniqueInput[]
  disconnect?: Prisma.ExportWhereUniqueInput | Prisma.ExportWhereUniqueInput[]
  delete?: Prisma.ExportWhereUniqueInput | Prisma.ExportWhereUniqueInput[]
  connect?: Prisma.ExportWhereUniqueInput | Prisma.ExportWhereUniqueInput[]
  update?: Prisma.ExportUpdateWithWhereUniqueWithoutUserInput | Prisma.ExportUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ExportUpdateManyWithWhereWithoutUserInput | Prisma.ExportUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ExportScalarWhereInput | Prisma.ExportScalarWhereInput[]
}

export type ExportCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  completed?: boolean
  path: string
  files: number
  size: string
}

export type ExportUncheckedCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  completed?: boolean
  path: string
  files: number
  size: string
}

export type ExportCreateOrConnectWithoutUserInput = {
  where: Prisma.ExportWhereUniqueInput
  create: Prisma.XOR<Prisma.ExportCreateWithoutUserInput, Prisma.ExportUncheckedCreateWithoutUserInput>
}

export type ExportCreateManyUserInputEnvelope = {
  data: Prisma.ExportCreateManyUserInput | Prisma.ExportCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ExportUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ExportWhereUniqueInput
  update: Prisma.XOR<Prisma.ExportUpdateWithoutUserInput, Prisma.ExportUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ExportCreateWithoutUserInput, Prisma.ExportUncheckedCreateWithoutUserInput>
}

export type ExportUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ExportWhereUniqueInput
  data: Prisma.XOR<Prisma.ExportUpdateWithoutUserInput, Prisma.ExportUncheckedUpdateWithoutUserInput>
}

export type ExportUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ExportScalarWhereInput
  data: Prisma.XOR<Prisma.ExportUpdateManyMutationInput, Prisma.ExportUncheckedUpdateManyWithoutUserInput>
}

export type ExportScalarWhereInput = {
  AND?: Prisma.ExportScalarWhereInput | Prisma.ExportScalarWhereInput[]
  OR?: Prisma.ExportScalarWhereInput[]
  NOT?: Prisma.ExportScalarWhereInput | Prisma.ExportScalarWhereInput[]
  id?: Prisma.StringFilter<"Export"> | string
  createdAt?: Prisma.DateTimeFilter<"Export"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Export"> | Date | string
  completed?: Prisma.BoolFilter<"Export"> | boolean
  path?: Prisma.StringFilter<"Export"> | string
  files?: Prisma.IntFilter<"Export"> | number
  size?: Prisma.StringFilter<"Export"> | string
  userId?: Prisma.StringFilter<"Export"> | string
}

export type ExportCreateManyUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  completed?: boolean
  path: string
  files: number
  size: string
}

export type ExportUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  path?: Prisma.StringFieldUpdateOperationsInput | string
  files?: Prisma.IntFieldUpdateOperationsInput | number
  size?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ExportUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  path?: Prisma.StringFieldUpdateOperationsInput | string
  files?: Prisma.IntFieldUpdateOperationsInput | number
  size?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ExportUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  path?: Prisma.StringFieldUpdateOperationsInput | string
  files?: Prisma.IntFieldUpdateOperationsInput | number
  size?: Prisma.StringFieldUpdateOperationsInput | string
}



export type ExportSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  completed?: boolean
  path?: boolean
  files?: boolean
  size?: boolean
  userId?: boolean
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["export"]>

export type ExportSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  completed?: boolean
  path?: boolean
  files?: boolean
  size?: boolean
  userId?: boolean
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["export"]>

export type ExportSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  completed?: boolean
  path?: boolean
  files?: boolean
  size?: boolean
  userId?: boolean
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["export"]>

export type ExportSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  completed?: boolean
  path?: boolean
  files?: boolean
  size?: boolean
  userId?: boolean
}

export type ExportOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "completed" | "path" | "files" | "size" | "userId", ExtArgs["result"]["export"]>
export type ExportInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ExportIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ExportIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $ExportPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Export"
  objects: {
    User: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    completed: boolean
    path: string
    files: number
    size: string
    userId: string
  }, ExtArgs["result"]["export"]>
  composites: {}
}

export type ExportGetPayload<S extends boolean | null | undefined | ExportDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ExportPayload, S>

export type ExportCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ExportFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ExportCountAggregateInputType | true
  }

export interface ExportDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Export'], meta: { name: 'Export' } }
  /**
   * Find zero or one Export that matches the filter.
   * @param {ExportFindUniqueArgs} args - Arguments to find a Export
   * @example
   * // Get one Export
   * const export = await prisma.export.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ExportFindUniqueArgs>(args: Prisma.SelectSubset<T, ExportFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ExportClient<runtime.Types.Result.GetResult<Prisma.$ExportPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Export that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ExportFindUniqueOrThrowArgs} args - Arguments to find a Export
   * @example
   * // Get one Export
   * const export = await prisma.export.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ExportFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ExportFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ExportClient<runtime.Types.Result.GetResult<Prisma.$ExportPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Export that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExportFindFirstArgs} args - Arguments to find a Export
   * @example
   * // Get one Export
   * const export = await prisma.export.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ExportFindFirstArgs>(args?: Prisma.SelectSubset<T, ExportFindFirstArgs<ExtArgs>>): Prisma.Prisma__ExportClient<runtime.Types.Result.GetResult<Prisma.$ExportPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Export that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExportFindFirstOrThrowArgs} args - Arguments to find a Export
   * @example
   * // Get one Export
   * const export = await prisma.export.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ExportFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ExportFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ExportClient<runtime.Types.Result.GetResult<Prisma.$ExportPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Exports that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExportFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Exports
   * const exports = await prisma.export.findMany()
   * 
   * // Get first 10 Exports
   * const exports = await prisma.export.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const exportWithIdOnly = await prisma.export.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ExportFindManyArgs>(args?: Prisma.SelectSubset<T, ExportFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExportPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Export.
   * @param {ExportCreateArgs} args - Arguments to create a Export.
   * @example
   * // Create one Export
   * const Export = await prisma.export.create({
   *   data: {
   *     // ... data to create a Export
   *   }
   * })
   * 
   */
  create<T extends ExportCreateArgs>(args: Prisma.SelectSubset<T, ExportCreateArgs<ExtArgs>>): Prisma.Prisma__ExportClient<runtime.Types.Result.GetResult<Prisma.$ExportPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Exports.
   * @param {ExportCreateManyArgs} args - Arguments to create many Exports.
   * @example
   * // Create many Exports
   * const export = await prisma.export.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ExportCreateManyArgs>(args?: Prisma.SelectSubset<T, ExportCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Exports and returns the data saved in the database.
   * @param {ExportCreateManyAndReturnArgs} args - Arguments to create many Exports.
   * @example
   * // Create many Exports
   * const export = await prisma.export.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Exports and only return the `id`
   * const exportWithIdOnly = await prisma.export.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ExportCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ExportCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExportPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Export.
   * @param {ExportDeleteArgs} args - Arguments to delete one Export.
   * @example
   * // Delete one Export
   * const Export = await prisma.export.delete({
   *   where: {
   *     // ... filter to delete one Export
   *   }
   * })
   * 
   */
  delete<T extends ExportDeleteArgs>(args: Prisma.SelectSubset<T, ExportDeleteArgs<ExtArgs>>): Prisma.Prisma__ExportClient<runtime.Types.Result.GetResult<Prisma.$ExportPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Export.
   * @param {ExportUpdateArgs} args - Arguments to update one Export.
   * @example
   * // Update one Export
   * const export = await prisma.export.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ExportUpdateArgs>(args: Prisma.SelectSubset<T, ExportUpdateArgs<ExtArgs>>): Prisma.Prisma__ExportClient<runtime.Types.Result.GetResult<Prisma.$ExportPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Exports.
   * @param {ExportDeleteManyArgs} args - Arguments to filter Exports to delete.
   * @example
   * // Delete a few Exports
   * const { count } = await prisma.export.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ExportDeleteManyArgs>(args?: Prisma.SelectSubset<T, ExportDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Exports.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExportUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Exports
   * const export = await prisma.export.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ExportUpdateManyArgs>(args: Prisma.SelectSubset<T, ExportUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Exports and returns the data updated in the database.
   * @param {ExportUpdateManyAndReturnArgs} args - Arguments to update many Exports.
   * @example
   * // Update many Exports
   * const export = await prisma.export.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Exports and only return the `id`
   * const exportWithIdOnly = await prisma.export.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ExportUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ExportUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExportPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Export.
   * @param {ExportUpsertArgs} args - Arguments to update or create a Export.
   * @example
   * // Update or create a Export
   * const export = await prisma.export.upsert({
   *   create: {
   *     // ... data to create a Export
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Export we want to update
   *   }
   * })
   */
  upsert<T extends ExportUpsertArgs>(args: Prisma.SelectSubset<T, ExportUpsertArgs<ExtArgs>>): Prisma.Prisma__ExportClient<runtime.Types.Result.GetResult<Prisma.$ExportPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Exports.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExportCountArgs} args - Arguments to filter Exports to count.
   * @example
   * // Count the number of Exports
   * const count = await prisma.export.count({
   *   where: {
   *     // ... the filter for the Exports we want to count
   *   }
   * })
  **/
  count<T extends ExportCountArgs>(
    args?: Prisma.Subset<T, ExportCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ExportCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Export.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExportAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ExportAggregateArgs>(args: Prisma.Subset<T, ExportAggregateArgs>): Prisma.PrismaPromise<GetExportAggregateType<T>>

  /**
   * Group by Export.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExportGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ExportGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ExportGroupByArgs['orderBy'] }
      : { orderBy?: ExportGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ExportGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetExportGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Export model
 */
readonly fields: ExportFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Export.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ExportClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  User<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Export model
 */
export interface ExportFieldRefs {
  readonly id: Prisma.FieldRef<"Export", 'String'>
  readonly createdAt: Prisma.FieldRef<"Export", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Export", 'DateTime'>
  readonly completed: Prisma.FieldRef<"Export", 'Boolean'>
  readonly path: Prisma.FieldRef<"Export", 'String'>
  readonly files: Prisma.FieldRef<"Export", 'Int'>
  readonly size: Prisma.FieldRef<"Export", 'String'>
  readonly userId: Prisma.FieldRef<"Export", 'String'>
}
    

// Custom InputTypes
/**
 * Export findUnique
 */
export type ExportFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Export
   */
  select?: Prisma.ExportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Export
   */
  omit?: Prisma.ExportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExportInclude<ExtArgs> | null
  /**
   * Filter, which Export to fetch.
   */
  where: Prisma.ExportWhereUniqueInput
}

/**
 * Export findUniqueOrThrow
 */
export type ExportFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Export
   */
  select?: Prisma.ExportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Export
   */
  omit?: Prisma.ExportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExportInclude<ExtArgs> | null
  /**
   * Filter, which Export to fetch.
   */
  where: Prisma.ExportWhereUniqueInput
}

/**
 * Export findFirst
 */
export type ExportFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Export
   */
  select?: Prisma.ExportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Export
   */
  omit?: Prisma.ExportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExportInclude<ExtArgs> | null
  /**
   * Filter, which Export to fetch.
   */
  where?: Prisma.ExportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Exports to fetch.
   */
  orderBy?: Prisma.ExportOrderByWithRelationInput | Prisma.ExportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Exports.
   */
  cursor?: Prisma.ExportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Exports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Exports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Exports.
   */
  distinct?: Prisma.ExportScalarFieldEnum | Prisma.ExportScalarFieldEnum[]
}

/**
 * Export findFirstOrThrow
 */
export type ExportFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Export
   */
  select?: Prisma.ExportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Export
   */
  omit?: Prisma.ExportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExportInclude<ExtArgs> | null
  /**
   * Filter, which Export to fetch.
   */
  where?: Prisma.ExportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Exports to fetch.
   */
  orderBy?: Prisma.ExportOrderByWithRelationInput | Prisma.ExportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Exports.
   */
  cursor?: Prisma.ExportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Exports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Exports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Exports.
   */
  distinct?: Prisma.ExportScalarFieldEnum | Prisma.ExportScalarFieldEnum[]
}

/**
 * Export findMany
 */
export type ExportFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Export
   */
  select?: Prisma.ExportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Export
   */
  omit?: Prisma.ExportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExportInclude<ExtArgs> | null
  /**
   * Filter, which Exports to fetch.
   */
  where?: Prisma.ExportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Exports to fetch.
   */
  orderBy?: Prisma.ExportOrderByWithRelationInput | Prisma.ExportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Exports.
   */
  cursor?: Prisma.ExportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Exports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Exports.
   */
  skip?: number
  distinct?: Prisma.ExportScalarFieldEnum | Prisma.ExportScalarFieldEnum[]
}

/**
 * Export create
 */
export type ExportCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Export
   */
  select?: Prisma.ExportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Export
   */
  omit?: Prisma.ExportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExportInclude<ExtArgs> | null
  /**
   * The data needed to create a Export.
   */
  data: Prisma.XOR<Prisma.ExportCreateInput, Prisma.ExportUncheckedCreateInput>
}

/**
 * Export createMany
 */
export type ExportCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Exports.
   */
  data: Prisma.ExportCreateManyInput | Prisma.ExportCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Export createManyAndReturn
 */
export type ExportCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Export
   */
  select?: Prisma.ExportSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Export
   */
  omit?: Prisma.ExportOmit<ExtArgs> | null
  /**
   * The data used to create many Exports.
   */
  data: Prisma.ExportCreateManyInput | Prisma.ExportCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExportIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Export update
 */
export type ExportUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Export
   */
  select?: Prisma.ExportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Export
   */
  omit?: Prisma.ExportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExportInclude<ExtArgs> | null
  /**
   * The data needed to update a Export.
   */
  data: Prisma.XOR<Prisma.ExportUpdateInput, Prisma.ExportUncheckedUpdateInput>
  /**
   * Choose, which Export to update.
   */
  where: Prisma.ExportWhereUniqueInput
}

/**
 * Export updateMany
 */
export type ExportUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Exports.
   */
  data: Prisma.XOR<Prisma.ExportUpdateManyMutationInput, Prisma.ExportUncheckedUpdateManyInput>
  /**
   * Filter which Exports to update
   */
  where?: Prisma.ExportWhereInput
  /**
   * Limit how many Exports to update.
   */
  limit?: number
}

/**
 * Export updateManyAndReturn
 */
export type ExportUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Export
   */
  select?: Prisma.ExportSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Export
   */
  omit?: Prisma.ExportOmit<ExtArgs> | null
  /**
   * The data used to update Exports.
   */
  data: Prisma.XOR<Prisma.ExportUpdateManyMutationInput, Prisma.ExportUncheckedUpdateManyInput>
  /**
   * Filter which Exports to update
   */
  where?: Prisma.ExportWhereInput
  /**
   * Limit how many Exports to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExportIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Export upsert
 */
export type ExportUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Export
   */
  select?: Prisma.ExportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Export
   */
  omit?: Prisma.ExportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExportInclude<ExtArgs> | null
  /**
   * The filter to search for the Export to update in case it exists.
   */
  where: Prisma.ExportWhereUniqueInput
  /**
   * In case the Export found by the `where` argument doesn't exist, create a new Export with this data.
   */
  create: Prisma.XOR<Prisma.ExportCreateInput, Prisma.ExportUncheckedCreateInput>
  /**
   * In case the Export was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ExportUpdateInput, Prisma.ExportUncheckedUpdateInput>
}

/**
 * Export delete
 */
export type ExportDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Export
   */
  select?: Prisma.ExportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Export
   */
  omit?: Prisma.ExportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExportInclude<ExtArgs> | null
  /**
   * Filter which Export to delete.
   */
  where: Prisma.ExportWhereUniqueInput
}

/**
 * Export deleteMany
 */
export type ExportDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Exports to delete
   */
  where?: Prisma.ExportWhereInput
  /**
   * Limit how many Exports to delete.
   */
  limit?: number
}

/**
 * Export without action
 */
export type ExportDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Export
   */
  select?: Prisma.ExportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Export
   */
  omit?: Prisma.ExportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExportInclude<ExtArgs> | null
}
