
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `Folder` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Folder
 * 
 */
export type FolderModel = runtime.Types.Result.DefaultSelection<Prisma.$FolderPayload>

export type AggregateFolder = {
  _count: FolderCountAggregateOutputType | null
  _min: FolderMinAggregateOutputType | null
  _max: FolderMaxAggregateOutputType | null
}

export type FolderMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  name: string | null
  public: boolean | null
  allowUploads: boolean | null
  userId: string | null
}

export type FolderMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  name: string | null
  public: boolean | null
  allowUploads: boolean | null
  userId: string | null
}

export type FolderCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  name: number
  public: number
  allowUploads: number
  userId: number
  _all: number
}


export type FolderMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  name?: true
  public?: true
  allowUploads?: true
  userId?: true
}

export type FolderMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  name?: true
  public?: true
  allowUploads?: true
  userId?: true
}

export type FolderCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  name?: true
  public?: true
  allowUploads?: true
  userId?: true
  _all?: true
}

export type FolderAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Folder to aggregate.
   */
  where?: Prisma.FolderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Folders to fetch.
   */
  orderBy?: Prisma.FolderOrderByWithRelationInput | Prisma.FolderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FolderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Folders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Folders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Folders
  **/
  _count?: true | FolderCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FolderMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FolderMaxAggregateInputType
}

export type GetFolderAggregateType<T extends FolderAggregateArgs> = {
      [P in keyof T & keyof AggregateFolder]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFolder[P]>
    : Prisma.GetScalarType<T[P], AggregateFolder[P]>
}




export type FolderGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FolderWhereInput
  orderBy?: Prisma.FolderOrderByWithAggregationInput | Prisma.FolderOrderByWithAggregationInput[]
  by: Prisma.FolderScalarFieldEnum[] | Prisma.FolderScalarFieldEnum
  having?: Prisma.FolderScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FolderCountAggregateInputType | true
  _min?: FolderMinAggregateInputType
  _max?: FolderMaxAggregateInputType
}

export type FolderGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  name: string
  public: boolean
  allowUploads: boolean
  userId: string
  _count: FolderCountAggregateOutputType | null
  _min: FolderMinAggregateOutputType | null
  _max: FolderMaxAggregateOutputType | null
}

type GetFolderGroupByPayload<T extends FolderGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FolderGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FolderGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FolderGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FolderGroupByOutputType[P]>
      }
    >
  >



export type FolderWhereInput = {
  AND?: Prisma.FolderWhereInput | Prisma.FolderWhereInput[]
  OR?: Prisma.FolderWhereInput[]
  NOT?: Prisma.FolderWhereInput | Prisma.FolderWhereInput[]
  id?: Prisma.StringFilter<"Folder"> | string
  createdAt?: Prisma.DateTimeFilter<"Folder"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Folder"> | Date | string
  name?: Prisma.StringFilter<"Folder"> | string
  public?: Prisma.BoolFilter<"Folder"> | boolean
  allowUploads?: Prisma.BoolFilter<"Folder"> | boolean
  userId?: Prisma.StringFilter<"Folder"> | string
  files?: Prisma.FileListRelationFilter
  User?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type FolderOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  public?: Prisma.SortOrder
  allowUploads?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  files?: Prisma.FileOrderByRelationAggregateInput
  User?: Prisma.UserOrderByWithRelationInput
}

export type FolderWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FolderWhereInput | Prisma.FolderWhereInput[]
  OR?: Prisma.FolderWhereInput[]
  NOT?: Prisma.FolderWhereInput | Prisma.FolderWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"Folder"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Folder"> | Date | string
  name?: Prisma.StringFilter<"Folder"> | string
  public?: Prisma.BoolFilter<"Folder"> | boolean
  allowUploads?: Prisma.BoolFilter<"Folder"> | boolean
  userId?: Prisma.StringFilter<"Folder"> | string
  files?: Prisma.FileListRelationFilter
  User?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type FolderOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  public?: Prisma.SortOrder
  allowUploads?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  _count?: Prisma.FolderCountOrderByAggregateInput
  _max?: Prisma.FolderMaxOrderByAggregateInput
  _min?: Prisma.FolderMinOrderByAggregateInput
}

export type FolderScalarWhereWithAggregatesInput = {
  AND?: Prisma.FolderScalarWhereWithAggregatesInput | Prisma.FolderScalarWhereWithAggregatesInput[]
  OR?: Prisma.FolderScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FolderScalarWhereWithAggregatesInput | Prisma.FolderScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Folder"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Folder"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Folder"> | Date | string
  name?: Prisma.StringWithAggregatesFilter<"Folder"> | string
  public?: Prisma.BoolWithAggregatesFilter<"Folder"> | boolean
  allowUploads?: Prisma.BoolWithAggregatesFilter<"Folder"> | boolean
  userId?: Prisma.StringWithAggregatesFilter<"Folder"> | string
}

export type FolderCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  public?: boolean
  allowUploads?: boolean
  files?: Prisma.FileCreateNestedManyWithoutFolderInput
  User: Prisma.UserCreateNestedOneWithoutFoldersInput
}

export type FolderUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  public?: boolean
  allowUploads?: boolean
  userId: string
  files?: Prisma.FileUncheckedCreateNestedManyWithoutFolderInput
}

export type FolderUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  public?: Prisma.BoolFieldUpdateOperationsInput | boolean
  allowUploads?: Prisma.BoolFieldUpdateOperationsInput | boolean
  files?: Prisma.FileUpdateManyWithoutFolderNestedInput
  User?: Prisma.UserUpdateOneRequiredWithoutFoldersNestedInput
}

export type FolderUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  public?: Prisma.BoolFieldUpdateOperationsInput | boolean
  allowUploads?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  files?: Prisma.FileUncheckedUpdateManyWithoutFolderNestedInput
}

export type FolderCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  public?: boolean
  allowUploads?: boolean
  userId: string
}

export type FolderUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  public?: Prisma.BoolFieldUpdateOperationsInput | boolean
  allowUploads?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type FolderUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  public?: Prisma.BoolFieldUpdateOperationsInput | boolean
  allowUploads?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FolderListRelationFilter = {
  every?: Prisma.FolderWhereInput
  some?: Prisma.FolderWhereInput
  none?: Prisma.FolderWhereInput
}

export type FolderOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FolderNullableScalarRelationFilter = {
  is?: Prisma.FolderWhereInput | null
  isNot?: Prisma.FolderWhereInput | null
}

export type FolderCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  public?: Prisma.SortOrder
  allowUploads?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type FolderMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  public?: Prisma.SortOrder
  allowUploads?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type FolderMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  public?: Prisma.SortOrder
  allowUploads?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type FolderCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.FolderCreateWithoutUserInput, Prisma.FolderUncheckedCreateWithoutUserInput> | Prisma.FolderCreateWithoutUserInput[] | Prisma.FolderUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FolderCreateOrConnectWithoutUserInput | Prisma.FolderCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.FolderCreateManyUserInputEnvelope
  connect?: Prisma.FolderWhereUniqueInput | Prisma.FolderWhereUniqueInput[]
}

export type FolderUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.FolderCreateWithoutUserInput, Prisma.FolderUncheckedCreateWithoutUserInput> | Prisma.FolderCreateWithoutUserInput[] | Prisma.FolderUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FolderCreateOrConnectWithoutUserInput | Prisma.FolderCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.FolderCreateManyUserInputEnvelope
  connect?: Prisma.FolderWhereUniqueInput | Prisma.FolderWhereUniqueInput[]
}

export type FolderUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.FolderCreateWithoutUserInput, Prisma.FolderUncheckedCreateWithoutUserInput> | Prisma.FolderCreateWithoutUserInput[] | Prisma.FolderUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FolderCreateOrConnectWithoutUserInput | Prisma.FolderCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.FolderUpsertWithWhereUniqueWithoutUserInput | Prisma.FolderUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.FolderCreateManyUserInputEnvelope
  set?: Prisma.FolderWhereUniqueInput | Prisma.FolderWhereUniqueInput[]
  disconnect?: Prisma.FolderWhereUniqueInput | Prisma.FolderWhereUniqueInput[]
  delete?: Prisma.FolderWhereUniqueInput | Prisma.FolderWhereUniqueInput[]
  connect?: Prisma.FolderWhereUniqueInput | Prisma.FolderWhereUniqueInput[]
  update?: Prisma.FolderUpdateWithWhereUniqueWithoutUserInput | Prisma.FolderUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.FolderUpdateManyWithWhereWithoutUserInput | Prisma.FolderUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.FolderScalarWhereInput | Prisma.FolderScalarWhereInput[]
}

export type FolderUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.FolderCreateWithoutUserInput, Prisma.FolderUncheckedCreateWithoutUserInput> | Prisma.FolderCreateWithoutUserInput[] | Prisma.FolderUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FolderCreateOrConnectWithoutUserInput | Prisma.FolderCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.FolderUpsertWithWhereUniqueWithoutUserInput | Prisma.FolderUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.FolderCreateManyUserInputEnvelope
  set?: Prisma.FolderWhereUniqueInput | Prisma.FolderWhereUniqueInput[]
  disconnect?: Prisma.FolderWhereUniqueInput | Prisma.FolderWhereUniqueInput[]
  delete?: Prisma.FolderWhereUniqueInput | Prisma.FolderWhereUniqueInput[]
  connect?: Prisma.FolderWhereUniqueInput | Prisma.FolderWhereUniqueInput[]
  update?: Prisma.FolderUpdateWithWhereUniqueWithoutUserInput | Prisma.FolderUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.FolderUpdateManyWithWhereWithoutUserInput | Prisma.FolderUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.FolderScalarWhereInput | Prisma.FolderScalarWhereInput[]
}

export type FolderCreateNestedOneWithoutFilesInput = {
  create?: Prisma.XOR<Prisma.FolderCreateWithoutFilesInput, Prisma.FolderUncheckedCreateWithoutFilesInput>
  connectOrCreate?: Prisma.FolderCreateOrConnectWithoutFilesInput
  connect?: Prisma.FolderWhereUniqueInput
}

export type FolderUpdateOneWithoutFilesNestedInput = {
  create?: Prisma.XOR<Prisma.FolderCreateWithoutFilesInput, Prisma.FolderUncheckedCreateWithoutFilesInput>
  connectOrCreate?: Prisma.FolderCreateOrConnectWithoutFilesInput
  upsert?: Prisma.FolderUpsertWithoutFilesInput
  disconnect?: Prisma.FolderWhereInput | boolean
  delete?: Prisma.FolderWhereInput | boolean
  connect?: Prisma.FolderWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FolderUpdateToOneWithWhereWithoutFilesInput, Prisma.FolderUpdateWithoutFilesInput>, Prisma.FolderUncheckedUpdateWithoutFilesInput>
}

export type FolderCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  public?: boolean
  allowUploads?: boolean
  files?: Prisma.FileCreateNestedManyWithoutFolderInput
}

export type FolderUncheckedCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  public?: boolean
  allowUploads?: boolean
  files?: Prisma.FileUncheckedCreateNestedManyWithoutFolderInput
}

export type FolderCreateOrConnectWithoutUserInput = {
  where: Prisma.FolderWhereUniqueInput
  create: Prisma.XOR<Prisma.FolderCreateWithoutUserInput, Prisma.FolderUncheckedCreateWithoutUserInput>
}

export type FolderCreateManyUserInputEnvelope = {
  data: Prisma.FolderCreateManyUserInput | Prisma.FolderCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type FolderUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.FolderWhereUniqueInput
  update: Prisma.XOR<Prisma.FolderUpdateWithoutUserInput, Prisma.FolderUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.FolderCreateWithoutUserInput, Prisma.FolderUncheckedCreateWithoutUserInput>
}

export type FolderUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.FolderWhereUniqueInput
  data: Prisma.XOR<Prisma.FolderUpdateWithoutUserInput, Prisma.FolderUncheckedUpdateWithoutUserInput>
}

export type FolderUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.FolderScalarWhereInput
  data: Prisma.XOR<Prisma.FolderUpdateManyMutationInput, Prisma.FolderUncheckedUpdateManyWithoutUserInput>
}

export type FolderScalarWhereInput = {
  AND?: Prisma.FolderScalarWhereInput | Prisma.FolderScalarWhereInput[]
  OR?: Prisma.FolderScalarWhereInput[]
  NOT?: Prisma.FolderScalarWhereInput | Prisma.FolderScalarWhereInput[]
  id?: Prisma.StringFilter<"Folder"> | string
  createdAt?: Prisma.DateTimeFilter<"Folder"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Folder"> | Date | string
  name?: Prisma.StringFilter<"Folder"> | string
  public?: Prisma.BoolFilter<"Folder"> | boolean
  allowUploads?: Prisma.BoolFilter<"Folder"> | boolean
  userId?: Prisma.StringFilter<"Folder"> | string
}

export type FolderCreateWithoutFilesInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  public?: boolean
  allowUploads?: boolean
  User: Prisma.UserCreateNestedOneWithoutFoldersInput
}

export type FolderUncheckedCreateWithoutFilesInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  public?: boolean
  allowUploads?: boolean
  userId: string
}

export type FolderCreateOrConnectWithoutFilesInput = {
  where: Prisma.FolderWhereUniqueInput
  create: Prisma.XOR<Prisma.FolderCreateWithoutFilesInput, Prisma.FolderUncheckedCreateWithoutFilesInput>
}

export type FolderUpsertWithoutFilesInput = {
  update: Prisma.XOR<Prisma.FolderUpdateWithoutFilesInput, Prisma.FolderUncheckedUpdateWithoutFilesInput>
  create: Prisma.XOR<Prisma.FolderCreateWithoutFilesInput, Prisma.FolderUncheckedCreateWithoutFilesInput>
  where?: Prisma.FolderWhereInput
}

export type FolderUpdateToOneWithWhereWithoutFilesInput = {
  where?: Prisma.FolderWhereInput
  data: Prisma.XOR<Prisma.FolderUpdateWithoutFilesInput, Prisma.FolderUncheckedUpdateWithoutFilesInput>
}

export type FolderUpdateWithoutFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  public?: Prisma.BoolFieldUpdateOperationsInput | boolean
  allowUploads?: Prisma.BoolFieldUpdateOperationsInput | boolean
  User?: Prisma.UserUpdateOneRequiredWithoutFoldersNestedInput
}

export type FolderUncheckedUpdateWithoutFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  public?: Prisma.BoolFieldUpdateOperationsInput | boolean
  allowUploads?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FolderCreateManyUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  public?: boolean
  allowUploads?: boolean
}

export type FolderUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  public?: Prisma.BoolFieldUpdateOperationsInput | boolean
  allowUploads?: Prisma.BoolFieldUpdateOperationsInput | boolean
  files?: Prisma.FileUpdateManyWithoutFolderNestedInput
}

export type FolderUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  public?: Prisma.BoolFieldUpdateOperationsInput | boolean
  allowUploads?: Prisma.BoolFieldUpdateOperationsInput | boolean
  files?: Prisma.FileUncheckedUpdateManyWithoutFolderNestedInput
}

export type FolderUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  public?: Prisma.BoolFieldUpdateOperationsInput | boolean
  allowUploads?: Prisma.BoolFieldUpdateOperationsInput | boolean
}


/**
 * Count Type FolderCountOutputType
 */

export type FolderCountOutputType = {
  files: number
}

export type FolderCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  files?: boolean | FolderCountOutputTypeCountFilesArgs
}

/**
 * FolderCountOutputType without action
 */
export type FolderCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FolderCountOutputType
   */
  select?: Prisma.FolderCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FolderCountOutputType without action
 */
export type FolderCountOutputTypeCountFilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FileWhereInput
}


export type FolderSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  name?: boolean
  public?: boolean
  allowUploads?: boolean
  userId?: boolean
  files?: boolean | Prisma.Folder$filesArgs<ExtArgs>
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.FolderCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["folder"]>

export type FolderSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  name?: boolean
  public?: boolean
  allowUploads?: boolean
  userId?: boolean
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["folder"]>

export type FolderSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  name?: boolean
  public?: boolean
  allowUploads?: boolean
  userId?: boolean
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["folder"]>

export type FolderSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  name?: boolean
  public?: boolean
  allowUploads?: boolean
  userId?: boolean
}

export type FolderOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "name" | "public" | "allowUploads" | "userId", ExtArgs["result"]["folder"]>
export type FolderInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  files?: boolean | Prisma.Folder$filesArgs<ExtArgs>
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.FolderCountOutputTypeDefaultArgs<ExtArgs>
}
export type FolderIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type FolderIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $FolderPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Folder"
  objects: {
    files: Prisma.$FilePayload<ExtArgs>[]
    User: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    name: string
    public: boolean
    allowUploads: boolean
    userId: string
  }, ExtArgs["result"]["folder"]>
  composites: {}
}

export type FolderGetPayload<S extends boolean | null | undefined | FolderDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FolderPayload, S>

export type FolderCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FolderFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FolderCountAggregateInputType | true
  }

export interface FolderDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Folder'], meta: { name: 'Folder' } }
  /**
   * Find zero or one Folder that matches the filter.
   * @param {FolderFindUniqueArgs} args - Arguments to find a Folder
   * @example
   * // Get one Folder
   * const folder = await prisma.folder.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FolderFindUniqueArgs>(args: Prisma.SelectSubset<T, FolderFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FolderClient<runtime.Types.Result.GetResult<Prisma.$FolderPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Folder that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FolderFindUniqueOrThrowArgs} args - Arguments to find a Folder
   * @example
   * // Get one Folder
   * const folder = await prisma.folder.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FolderFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FolderFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FolderClient<runtime.Types.Result.GetResult<Prisma.$FolderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Folder that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FolderFindFirstArgs} args - Arguments to find a Folder
   * @example
   * // Get one Folder
   * const folder = await prisma.folder.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FolderFindFirstArgs>(args?: Prisma.SelectSubset<T, FolderFindFirstArgs<ExtArgs>>): Prisma.Prisma__FolderClient<runtime.Types.Result.GetResult<Prisma.$FolderPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Folder that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FolderFindFirstOrThrowArgs} args - Arguments to find a Folder
   * @example
   * // Get one Folder
   * const folder = await prisma.folder.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FolderFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FolderFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FolderClient<runtime.Types.Result.GetResult<Prisma.$FolderPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Folders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FolderFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Folders
   * const folders = await prisma.folder.findMany()
   * 
   * // Get first 10 Folders
   * const folders = await prisma.folder.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const folderWithIdOnly = await prisma.folder.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FolderFindManyArgs>(args?: Prisma.SelectSubset<T, FolderFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FolderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Folder.
   * @param {FolderCreateArgs} args - Arguments to create a Folder.
   * @example
   * // Create one Folder
   * const Folder = await prisma.folder.create({
   *   data: {
   *     // ... data to create a Folder
   *   }
   * })
   * 
   */
  create<T extends FolderCreateArgs>(args: Prisma.SelectSubset<T, FolderCreateArgs<ExtArgs>>): Prisma.Prisma__FolderClient<runtime.Types.Result.GetResult<Prisma.$FolderPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Folders.
   * @param {FolderCreateManyArgs} args - Arguments to create many Folders.
   * @example
   * // Create many Folders
   * const folder = await prisma.folder.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FolderCreateManyArgs>(args?: Prisma.SelectSubset<T, FolderCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Folders and returns the data saved in the database.
   * @param {FolderCreateManyAndReturnArgs} args - Arguments to create many Folders.
   * @example
   * // Create many Folders
   * const folder = await prisma.folder.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Folders and only return the `id`
   * const folderWithIdOnly = await prisma.folder.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FolderCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FolderCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FolderPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Folder.
   * @param {FolderDeleteArgs} args - Arguments to delete one Folder.
   * @example
   * // Delete one Folder
   * const Folder = await prisma.folder.delete({
   *   where: {
   *     // ... filter to delete one Folder
   *   }
   * })
   * 
   */
  delete<T extends FolderDeleteArgs>(args: Prisma.SelectSubset<T, FolderDeleteArgs<ExtArgs>>): Prisma.Prisma__FolderClient<runtime.Types.Result.GetResult<Prisma.$FolderPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Folder.
   * @param {FolderUpdateArgs} args - Arguments to update one Folder.
   * @example
   * // Update one Folder
   * const folder = await prisma.folder.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FolderUpdateArgs>(args: Prisma.SelectSubset<T, FolderUpdateArgs<ExtArgs>>): Prisma.Prisma__FolderClient<runtime.Types.Result.GetResult<Prisma.$FolderPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Folders.
   * @param {FolderDeleteManyArgs} args - Arguments to filter Folders to delete.
   * @example
   * // Delete a few Folders
   * const { count } = await prisma.folder.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FolderDeleteManyArgs>(args?: Prisma.SelectSubset<T, FolderDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Folders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FolderUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Folders
   * const folder = await prisma.folder.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FolderUpdateManyArgs>(args: Prisma.SelectSubset<T, FolderUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Folders and returns the data updated in the database.
   * @param {FolderUpdateManyAndReturnArgs} args - Arguments to update many Folders.
   * @example
   * // Update many Folders
   * const folder = await prisma.folder.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Folders and only return the `id`
   * const folderWithIdOnly = await prisma.folder.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FolderUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FolderUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FolderPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Folder.
   * @param {FolderUpsertArgs} args - Arguments to update or create a Folder.
   * @example
   * // Update or create a Folder
   * const folder = await prisma.folder.upsert({
   *   create: {
   *     // ... data to create a Folder
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Folder we want to update
   *   }
   * })
   */
  upsert<T extends FolderUpsertArgs>(args: Prisma.SelectSubset<T, FolderUpsertArgs<ExtArgs>>): Prisma.Prisma__FolderClient<runtime.Types.Result.GetResult<Prisma.$FolderPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Folders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FolderCountArgs} args - Arguments to filter Folders to count.
   * @example
   * // Count the number of Folders
   * const count = await prisma.folder.count({
   *   where: {
   *     // ... the filter for the Folders we want to count
   *   }
   * })
  **/
  count<T extends FolderCountArgs>(
    args?: Prisma.Subset<T, FolderCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FolderCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Folder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FolderAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FolderAggregateArgs>(args: Prisma.Subset<T, FolderAggregateArgs>): Prisma.PrismaPromise<GetFolderAggregateType<T>>

  /**
   * Group by Folder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FolderGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FolderGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FolderGroupByArgs['orderBy'] }
      : { orderBy?: FolderGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FolderGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFolderGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Folder model
 */
readonly fields: FolderFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Folder.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FolderClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  files<T extends Prisma.Folder$filesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Folder$filesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  User<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Folder model
 */
export interface FolderFieldRefs {
  readonly id: Prisma.FieldRef<"Folder", 'String'>
  readonly createdAt: Prisma.FieldRef<"Folder", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Folder", 'DateTime'>
  readonly name: Prisma.FieldRef<"Folder", 'String'>
  readonly public: Prisma.FieldRef<"Folder", 'Boolean'>
  readonly allowUploads: Prisma.FieldRef<"Folder", 'Boolean'>
  readonly userId: Prisma.FieldRef<"Folder", 'String'>
}
    

// Custom InputTypes
/**
 * Folder findUnique
 */
export type FolderFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folder
   */
  select?: Prisma.FolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folder
   */
  omit?: Prisma.FolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FolderInclude<ExtArgs> | null
  /**
   * Filter, which Folder to fetch.
   */
  where: Prisma.FolderWhereUniqueInput
}

/**
 * Folder findUniqueOrThrow
 */
export type FolderFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folder
   */
  select?: Prisma.FolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folder
   */
  omit?: Prisma.FolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FolderInclude<ExtArgs> | null
  /**
   * Filter, which Folder to fetch.
   */
  where: Prisma.FolderWhereUniqueInput
}

/**
 * Folder findFirst
 */
export type FolderFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folder
   */
  select?: Prisma.FolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folder
   */
  omit?: Prisma.FolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FolderInclude<ExtArgs> | null
  /**
   * Filter, which Folder to fetch.
   */
  where?: Prisma.FolderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Folders to fetch.
   */
  orderBy?: Prisma.FolderOrderByWithRelationInput | Prisma.FolderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Folders.
   */
  cursor?: Prisma.FolderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Folders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Folders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Folders.
   */
  distinct?: Prisma.FolderScalarFieldEnum | Prisma.FolderScalarFieldEnum[]
}

/**
 * Folder findFirstOrThrow
 */
export type FolderFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folder
   */
  select?: Prisma.FolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folder
   */
  omit?: Prisma.FolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FolderInclude<ExtArgs> | null
  /**
   * Filter, which Folder to fetch.
   */
  where?: Prisma.FolderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Folders to fetch.
   */
  orderBy?: Prisma.FolderOrderByWithRelationInput | Prisma.FolderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Folders.
   */
  cursor?: Prisma.FolderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Folders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Folders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Folders.
   */
  distinct?: Prisma.FolderScalarFieldEnum | Prisma.FolderScalarFieldEnum[]
}

/**
 * Folder findMany
 */
export type FolderFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folder
   */
  select?: Prisma.FolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folder
   */
  omit?: Prisma.FolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FolderInclude<ExtArgs> | null
  /**
   * Filter, which Folders to fetch.
   */
  where?: Prisma.FolderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Folders to fetch.
   */
  orderBy?: Prisma.FolderOrderByWithRelationInput | Prisma.FolderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Folders.
   */
  cursor?: Prisma.FolderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Folders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Folders.
   */
  skip?: number
  distinct?: Prisma.FolderScalarFieldEnum | Prisma.FolderScalarFieldEnum[]
}

/**
 * Folder create
 */
export type FolderCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folder
   */
  select?: Prisma.FolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folder
   */
  omit?: Prisma.FolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FolderInclude<ExtArgs> | null
  /**
   * The data needed to create a Folder.
   */
  data: Prisma.XOR<Prisma.FolderCreateInput, Prisma.FolderUncheckedCreateInput>
}

/**
 * Folder createMany
 */
export type FolderCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Folders.
   */
  data: Prisma.FolderCreateManyInput | Prisma.FolderCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Folder createManyAndReturn
 */
export type FolderCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folder
   */
  select?: Prisma.FolderSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Folder
   */
  omit?: Prisma.FolderOmit<ExtArgs> | null
  /**
   * The data used to create many Folders.
   */
  data: Prisma.FolderCreateManyInput | Prisma.FolderCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FolderIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Folder update
 */
export type FolderUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folder
   */
  select?: Prisma.FolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folder
   */
  omit?: Prisma.FolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FolderInclude<ExtArgs> | null
  /**
   * The data needed to update a Folder.
   */
  data: Prisma.XOR<Prisma.FolderUpdateInput, Prisma.FolderUncheckedUpdateInput>
  /**
   * Choose, which Folder to update.
   */
  where: Prisma.FolderWhereUniqueInput
}

/**
 * Folder updateMany
 */
export type FolderUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Folders.
   */
  data: Prisma.XOR<Prisma.FolderUpdateManyMutationInput, Prisma.FolderUncheckedUpdateManyInput>
  /**
   * Filter which Folders to update
   */
  where?: Prisma.FolderWhereInput
  /**
   * Limit how many Folders to update.
   */
  limit?: number
}

/**
 * Folder updateManyAndReturn
 */
export type FolderUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folder
   */
  select?: Prisma.FolderSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Folder
   */
  omit?: Prisma.FolderOmit<ExtArgs> | null
  /**
   * The data used to update Folders.
   */
  data: Prisma.XOR<Prisma.FolderUpdateManyMutationInput, Prisma.FolderUncheckedUpdateManyInput>
  /**
   * Filter which Folders to update
   */
  where?: Prisma.FolderWhereInput
  /**
   * Limit how many Folders to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FolderIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Folder upsert
 */
export type FolderUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folder
   */
  select?: Prisma.FolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folder
   */
  omit?: Prisma.FolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FolderInclude<ExtArgs> | null
  /**
   * The filter to search for the Folder to update in case it exists.
   */
  where: Prisma.FolderWhereUniqueInput
  /**
   * In case the Folder found by the `where` argument doesn't exist, create a new Folder with this data.
   */
  create: Prisma.XOR<Prisma.FolderCreateInput, Prisma.FolderUncheckedCreateInput>
  /**
   * In case the Folder was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FolderUpdateInput, Prisma.FolderUncheckedUpdateInput>
}

/**
 * Folder delete
 */
export type FolderDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folder
   */
  select?: Prisma.FolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folder
   */
  omit?: Prisma.FolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FolderInclude<ExtArgs> | null
  /**
   * Filter which Folder to delete.
   */
  where: Prisma.FolderWhereUniqueInput
}

/**
 * Folder deleteMany
 */
export type FolderDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Folders to delete
   */
  where?: Prisma.FolderWhereInput
  /**
   * Limit how many Folders to delete.
   */
  limit?: number
}

/**
 * Folder.files
 */
export type Folder$filesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the File
   */
  select?: Prisma.FileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the File
   */
  omit?: Prisma.FileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileInclude<ExtArgs> | null
  where?: Prisma.FileWhereInput
  orderBy?: Prisma.FileOrderByWithRelationInput | Prisma.FileOrderByWithRelationInput[]
  cursor?: Prisma.FileWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FileScalarFieldEnum | Prisma.FileScalarFieldEnum[]
}

/**
 * Folder without action
 */
export type FolderDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folder
   */
  select?: Prisma.FolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folder
   */
  omit?: Prisma.FolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FolderInclude<ExtArgs> | null
}
