
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `OAuthProvider` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model OAuthProvider
 * 
 */
export type OAuthProviderModel = runtime.Types.Result.DefaultSelection<Prisma.$OAuthProviderPayload>

export type AggregateOAuthProvider = {
  _count: OAuthProviderCountAggregateOutputType | null
  _min: OAuthProviderMinAggregateOutputType | null
  _max: OAuthProviderMaxAggregateOutputType | null
}

export type OAuthProviderMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
  provider: $Enums.OAuthProviderType | null
  username: string | null
  accessToken: string | null
  refreshToken: string | null
  oauthId: string | null
}

export type OAuthProviderMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
  provider: $Enums.OAuthProviderType | null
  username: string | null
  accessToken: string | null
  refreshToken: string | null
  oauthId: string | null
}

export type OAuthProviderCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  userId: number
  provider: number
  username: number
  accessToken: number
  refreshToken: number
  oauthId: number
  _all: number
}


export type OAuthProviderMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  provider?: true
  username?: true
  accessToken?: true
  refreshToken?: true
  oauthId?: true
}

export type OAuthProviderMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  provider?: true
  username?: true
  accessToken?: true
  refreshToken?: true
  oauthId?: true
}

export type OAuthProviderCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  provider?: true
  username?: true
  accessToken?: true
  refreshToken?: true
  oauthId?: true
  _all?: true
}

export type OAuthProviderAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OAuthProvider to aggregate.
   */
  where?: Prisma.OAuthProviderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OAuthProviders to fetch.
   */
  orderBy?: Prisma.OAuthProviderOrderByWithRelationInput | Prisma.OAuthProviderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.OAuthProviderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OAuthProviders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OAuthProviders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned OAuthProviders
  **/
  _count?: true | OAuthProviderCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OAuthProviderMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OAuthProviderMaxAggregateInputType
}

export type GetOAuthProviderAggregateType<T extends OAuthProviderAggregateArgs> = {
      [P in keyof T & keyof AggregateOAuthProvider]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOAuthProvider[P]>
    : Prisma.GetScalarType<T[P], AggregateOAuthProvider[P]>
}




export type OAuthProviderGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OAuthProviderWhereInput
  orderBy?: Prisma.OAuthProviderOrderByWithAggregationInput | Prisma.OAuthProviderOrderByWithAggregationInput[]
  by: Prisma.OAuthProviderScalarFieldEnum[] | Prisma.OAuthProviderScalarFieldEnum
  having?: Prisma.OAuthProviderScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OAuthProviderCountAggregateInputType | true
  _min?: OAuthProviderMinAggregateInputType
  _max?: OAuthProviderMaxAggregateInputType
}

export type OAuthProviderGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  userId: string
  provider: $Enums.OAuthProviderType
  username: string
  accessToken: string
  refreshToken: string | null
  oauthId: string | null
  _count: OAuthProviderCountAggregateOutputType | null
  _min: OAuthProviderMinAggregateOutputType | null
  _max: OAuthProviderMaxAggregateOutputType | null
}

type GetOAuthProviderGroupByPayload<T extends OAuthProviderGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OAuthProviderGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OAuthProviderGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OAuthProviderGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OAuthProviderGroupByOutputType[P]>
      }
    >
  >



export type OAuthProviderWhereInput = {
  AND?: Prisma.OAuthProviderWhereInput | Prisma.OAuthProviderWhereInput[]
  OR?: Prisma.OAuthProviderWhereInput[]
  NOT?: Prisma.OAuthProviderWhereInput | Prisma.OAuthProviderWhereInput[]
  id?: Prisma.StringFilter<"OAuthProvider"> | string
  createdAt?: Prisma.DateTimeFilter<"OAuthProvider"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OAuthProvider"> | Date | string
  userId?: Prisma.StringFilter<"OAuthProvider"> | string
  provider?: Prisma.EnumOAuthProviderTypeFilter<"OAuthProvider"> | $Enums.OAuthProviderType
  username?: Prisma.StringFilter<"OAuthProvider"> | string
  accessToken?: Prisma.StringFilter<"OAuthProvider"> | string
  refreshToken?: Prisma.StringNullableFilter<"OAuthProvider"> | string | null
  oauthId?: Prisma.StringNullableFilter<"OAuthProvider"> | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type OAuthProviderOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  username?: Prisma.SortOrder
  accessToken?: Prisma.SortOrder
  refreshToken?: Prisma.SortOrderInput | Prisma.SortOrder
  oauthId?: Prisma.SortOrderInput | Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type OAuthProviderWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  provider_oauthId?: Prisma.OAuthProviderProviderOauthIdCompoundUniqueInput
  AND?: Prisma.OAuthProviderWhereInput | Prisma.OAuthProviderWhereInput[]
  OR?: Prisma.OAuthProviderWhereInput[]
  NOT?: Prisma.OAuthProviderWhereInput | Prisma.OAuthProviderWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"OAuthProvider"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OAuthProvider"> | Date | string
  userId?: Prisma.StringFilter<"OAuthProvider"> | string
  provider?: Prisma.EnumOAuthProviderTypeFilter<"OAuthProvider"> | $Enums.OAuthProviderType
  username?: Prisma.StringFilter<"OAuthProvider"> | string
  accessToken?: Prisma.StringFilter<"OAuthProvider"> | string
  refreshToken?: Prisma.StringNullableFilter<"OAuthProvider"> | string | null
  oauthId?: Prisma.StringNullableFilter<"OAuthProvider"> | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "provider_oauthId">

export type OAuthProviderOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  username?: Prisma.SortOrder
  accessToken?: Prisma.SortOrder
  refreshToken?: Prisma.SortOrderInput | Prisma.SortOrder
  oauthId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.OAuthProviderCountOrderByAggregateInput
  _max?: Prisma.OAuthProviderMaxOrderByAggregateInput
  _min?: Prisma.OAuthProviderMinOrderByAggregateInput
}

export type OAuthProviderScalarWhereWithAggregatesInput = {
  AND?: Prisma.OAuthProviderScalarWhereWithAggregatesInput | Prisma.OAuthProviderScalarWhereWithAggregatesInput[]
  OR?: Prisma.OAuthProviderScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OAuthProviderScalarWhereWithAggregatesInput | Prisma.OAuthProviderScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"OAuthProvider"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"OAuthProvider"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"OAuthProvider"> | Date | string
  userId?: Prisma.StringWithAggregatesFilter<"OAuthProvider"> | string
  provider?: Prisma.EnumOAuthProviderTypeWithAggregatesFilter<"OAuthProvider"> | $Enums.OAuthProviderType
  username?: Prisma.StringWithAggregatesFilter<"OAuthProvider"> | string
  accessToken?: Prisma.StringWithAggregatesFilter<"OAuthProvider"> | string
  refreshToken?: Prisma.StringNullableWithAggregatesFilter<"OAuthProvider"> | string | null
  oauthId?: Prisma.StringNullableWithAggregatesFilter<"OAuthProvider"> | string | null
}

export type OAuthProviderCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  provider: $Enums.OAuthProviderType
  username: string
  accessToken: string
  refreshToken?: string | null
  oauthId?: string | null
  user: Prisma.UserCreateNestedOneWithoutOauthProvidersInput
}

export type OAuthProviderUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: string
  provider: $Enums.OAuthProviderType
  username: string
  accessToken: string
  refreshToken?: string | null
  oauthId?: string | null
}

export type OAuthProviderUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  provider?: Prisma.EnumOAuthProviderTypeFieldUpdateOperationsInput | $Enums.OAuthProviderType
  username?: Prisma.StringFieldUpdateOperationsInput | string
  accessToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  oauthId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutOauthProvidersNestedInput
}

export type OAuthProviderUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumOAuthProviderTypeFieldUpdateOperationsInput | $Enums.OAuthProviderType
  username?: Prisma.StringFieldUpdateOperationsInput | string
  accessToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  oauthId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type OAuthProviderCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: string
  provider: $Enums.OAuthProviderType
  username: string
  accessToken: string
  refreshToken?: string | null
  oauthId?: string | null
}

export type OAuthProviderUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  provider?: Prisma.EnumOAuthProviderTypeFieldUpdateOperationsInput | $Enums.OAuthProviderType
  username?: Prisma.StringFieldUpdateOperationsInput | string
  accessToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  oauthId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type OAuthProviderUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumOAuthProviderTypeFieldUpdateOperationsInput | $Enums.OAuthProviderType
  username?: Prisma.StringFieldUpdateOperationsInput | string
  accessToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  oauthId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type OAuthProviderListRelationFilter = {
  every?: Prisma.OAuthProviderWhereInput
  some?: Prisma.OAuthProviderWhereInput
  none?: Prisma.OAuthProviderWhereInput
}

export type OAuthProviderOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type OAuthProviderProviderOauthIdCompoundUniqueInput = {
  provider: $Enums.OAuthProviderType
  oauthId: string
}

export type OAuthProviderCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  username?: Prisma.SortOrder
  accessToken?: Prisma.SortOrder
  refreshToken?: Prisma.SortOrder
  oauthId?: Prisma.SortOrder
}

export type OAuthProviderMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  username?: Prisma.SortOrder
  accessToken?: Prisma.SortOrder
  refreshToken?: Prisma.SortOrder
  oauthId?: Prisma.SortOrder
}

export type OAuthProviderMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  username?: Prisma.SortOrder
  accessToken?: Prisma.SortOrder
  refreshToken?: Prisma.SortOrder
  oauthId?: Prisma.SortOrder
}

export type OAuthProviderCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.OAuthProviderCreateWithoutUserInput, Prisma.OAuthProviderUncheckedCreateWithoutUserInput> | Prisma.OAuthProviderCreateWithoutUserInput[] | Prisma.OAuthProviderUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.OAuthProviderCreateOrConnectWithoutUserInput | Prisma.OAuthProviderCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.OAuthProviderCreateManyUserInputEnvelope
  connect?: Prisma.OAuthProviderWhereUniqueInput | Prisma.OAuthProviderWhereUniqueInput[]
}

export type OAuthProviderUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.OAuthProviderCreateWithoutUserInput, Prisma.OAuthProviderUncheckedCreateWithoutUserInput> | Prisma.OAuthProviderCreateWithoutUserInput[] | Prisma.OAuthProviderUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.OAuthProviderCreateOrConnectWithoutUserInput | Prisma.OAuthProviderCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.OAuthProviderCreateManyUserInputEnvelope
  connect?: Prisma.OAuthProviderWhereUniqueInput | Prisma.OAuthProviderWhereUniqueInput[]
}

export type OAuthProviderUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.OAuthProviderCreateWithoutUserInput, Prisma.OAuthProviderUncheckedCreateWithoutUserInput> | Prisma.OAuthProviderCreateWithoutUserInput[] | Prisma.OAuthProviderUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.OAuthProviderCreateOrConnectWithoutUserInput | Prisma.OAuthProviderCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.OAuthProviderUpsertWithWhereUniqueWithoutUserInput | Prisma.OAuthProviderUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.OAuthProviderCreateManyUserInputEnvelope
  set?: Prisma.OAuthProviderWhereUniqueInput | Prisma.OAuthProviderWhereUniqueInput[]
  disconnect?: Prisma.OAuthProviderWhereUniqueInput | Prisma.OAuthProviderWhereUniqueInput[]
  delete?: Prisma.OAuthProviderWhereUniqueInput | Prisma.OAuthProviderWhereUniqueInput[]
  connect?: Prisma.OAuthProviderWhereUniqueInput | Prisma.OAuthProviderWhereUniqueInput[]
  update?: Prisma.OAuthProviderUpdateWithWhereUniqueWithoutUserInput | Prisma.OAuthProviderUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.OAuthProviderUpdateManyWithWhereWithoutUserInput | Prisma.OAuthProviderUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.OAuthProviderScalarWhereInput | Prisma.OAuthProviderScalarWhereInput[]
}

export type OAuthProviderUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.OAuthProviderCreateWithoutUserInput, Prisma.OAuthProviderUncheckedCreateWithoutUserInput> | Prisma.OAuthProviderCreateWithoutUserInput[] | Prisma.OAuthProviderUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.OAuthProviderCreateOrConnectWithoutUserInput | Prisma.OAuthProviderCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.OAuthProviderUpsertWithWhereUniqueWithoutUserInput | Prisma.OAuthProviderUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.OAuthProviderCreateManyUserInputEnvelope
  set?: Prisma.OAuthProviderWhereUniqueInput | Prisma.OAuthProviderWhereUniqueInput[]
  disconnect?: Prisma.OAuthProviderWhereUniqueInput | Prisma.OAuthProviderWhereUniqueInput[]
  delete?: Prisma.OAuthProviderWhereUniqueInput | Prisma.OAuthProviderWhereUniqueInput[]
  connect?: Prisma.OAuthProviderWhereUniqueInput | Prisma.OAuthProviderWhereUniqueInput[]
  update?: Prisma.OAuthProviderUpdateWithWhereUniqueWithoutUserInput | Prisma.OAuthProviderUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.OAuthProviderUpdateManyWithWhereWithoutUserInput | Prisma.OAuthProviderUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.OAuthProviderScalarWhereInput | Prisma.OAuthProviderScalarWhereInput[]
}

export type EnumOAuthProviderTypeFieldUpdateOperationsInput = {
  set?: $Enums.OAuthProviderType
}

export type OAuthProviderCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  provider: $Enums.OAuthProviderType
  username: string
  accessToken: string
  refreshToken?: string | null
  oauthId?: string | null
}

export type OAuthProviderUncheckedCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  provider: $Enums.OAuthProviderType
  username: string
  accessToken: string
  refreshToken?: string | null
  oauthId?: string | null
}

export type OAuthProviderCreateOrConnectWithoutUserInput = {
  where: Prisma.OAuthProviderWhereUniqueInput
  create: Prisma.XOR<Prisma.OAuthProviderCreateWithoutUserInput, Prisma.OAuthProviderUncheckedCreateWithoutUserInput>
}

export type OAuthProviderCreateManyUserInputEnvelope = {
  data: Prisma.OAuthProviderCreateManyUserInput | Prisma.OAuthProviderCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type OAuthProviderUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.OAuthProviderWhereUniqueInput
  update: Prisma.XOR<Prisma.OAuthProviderUpdateWithoutUserInput, Prisma.OAuthProviderUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.OAuthProviderCreateWithoutUserInput, Prisma.OAuthProviderUncheckedCreateWithoutUserInput>
}

export type OAuthProviderUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.OAuthProviderWhereUniqueInput
  data: Prisma.XOR<Prisma.OAuthProviderUpdateWithoutUserInput, Prisma.OAuthProviderUncheckedUpdateWithoutUserInput>
}

export type OAuthProviderUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.OAuthProviderScalarWhereInput
  data: Prisma.XOR<Prisma.OAuthProviderUpdateManyMutationInput, Prisma.OAuthProviderUncheckedUpdateManyWithoutUserInput>
}

export type OAuthProviderScalarWhereInput = {
  AND?: Prisma.OAuthProviderScalarWhereInput | Prisma.OAuthProviderScalarWhereInput[]
  OR?: Prisma.OAuthProviderScalarWhereInput[]
  NOT?: Prisma.OAuthProviderScalarWhereInput | Prisma.OAuthProviderScalarWhereInput[]
  id?: Prisma.StringFilter<"OAuthProvider"> | string
  createdAt?: Prisma.DateTimeFilter<"OAuthProvider"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OAuthProvider"> | Date | string
  userId?: Prisma.StringFilter<"OAuthProvider"> | string
  provider?: Prisma.EnumOAuthProviderTypeFilter<"OAuthProvider"> | $Enums.OAuthProviderType
  username?: Prisma.StringFilter<"OAuthProvider"> | string
  accessToken?: Prisma.StringFilter<"OAuthProvider"> | string
  refreshToken?: Prisma.StringNullableFilter<"OAuthProvider"> | string | null
  oauthId?: Prisma.StringNullableFilter<"OAuthProvider"> | string | null
}

export type OAuthProviderCreateManyUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  provider: $Enums.OAuthProviderType
  username: string
  accessToken: string
  refreshToken?: string | null
  oauthId?: string | null
}

export type OAuthProviderUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  provider?: Prisma.EnumOAuthProviderTypeFieldUpdateOperationsInput | $Enums.OAuthProviderType
  username?: Prisma.StringFieldUpdateOperationsInput | string
  accessToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  oauthId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type OAuthProviderUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  provider?: Prisma.EnumOAuthProviderTypeFieldUpdateOperationsInput | $Enums.OAuthProviderType
  username?: Prisma.StringFieldUpdateOperationsInput | string
  accessToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  oauthId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type OAuthProviderUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  provider?: Prisma.EnumOAuthProviderTypeFieldUpdateOperationsInput | $Enums.OAuthProviderType
  username?: Prisma.StringFieldUpdateOperationsInput | string
  accessToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  oauthId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type OAuthProviderSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  provider?: boolean
  username?: boolean
  accessToken?: boolean
  refreshToken?: boolean
  oauthId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["oAuthProvider"]>

export type OAuthProviderSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  provider?: boolean
  username?: boolean
  accessToken?: boolean
  refreshToken?: boolean
  oauthId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["oAuthProvider"]>

export type OAuthProviderSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  provider?: boolean
  username?: boolean
  accessToken?: boolean
  refreshToken?: boolean
  oauthId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["oAuthProvider"]>

export type OAuthProviderSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  provider?: boolean
  username?: boolean
  accessToken?: boolean
  refreshToken?: boolean
  oauthId?: boolean
}

export type OAuthProviderOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "userId" | "provider" | "username" | "accessToken" | "refreshToken" | "oauthId", ExtArgs["result"]["oAuthProvider"]>
export type OAuthProviderInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type OAuthProviderIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type OAuthProviderIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $OAuthProviderPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "OAuthProvider"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    userId: string
    provider: $Enums.OAuthProviderType
    username: string
    accessToken: string
    refreshToken: string | null
    oauthId: string | null
  }, ExtArgs["result"]["oAuthProvider"]>
  composites: {}
}

export type OAuthProviderGetPayload<S extends boolean | null | undefined | OAuthProviderDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OAuthProviderPayload, S>

export type OAuthProviderCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OAuthProviderFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OAuthProviderCountAggregateInputType | true
  }

export interface OAuthProviderDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['OAuthProvider'], meta: { name: 'OAuthProvider' } }
  /**
   * Find zero or one OAuthProvider that matches the filter.
   * @param {OAuthProviderFindUniqueArgs} args - Arguments to find a OAuthProvider
   * @example
   * // Get one OAuthProvider
   * const oAuthProvider = await prisma.oAuthProvider.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OAuthProviderFindUniqueArgs>(args: Prisma.SelectSubset<T, OAuthProviderFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OAuthProviderClient<runtime.Types.Result.GetResult<Prisma.$OAuthProviderPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OAuthProvider that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OAuthProviderFindUniqueOrThrowArgs} args - Arguments to find a OAuthProvider
   * @example
   * // Get one OAuthProvider
   * const oAuthProvider = await prisma.oAuthProvider.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OAuthProviderFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OAuthProviderFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OAuthProviderClient<runtime.Types.Result.GetResult<Prisma.$OAuthProviderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OAuthProvider that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OAuthProviderFindFirstArgs} args - Arguments to find a OAuthProvider
   * @example
   * // Get one OAuthProvider
   * const oAuthProvider = await prisma.oAuthProvider.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OAuthProviderFindFirstArgs>(args?: Prisma.SelectSubset<T, OAuthProviderFindFirstArgs<ExtArgs>>): Prisma.Prisma__OAuthProviderClient<runtime.Types.Result.GetResult<Prisma.$OAuthProviderPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OAuthProvider that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OAuthProviderFindFirstOrThrowArgs} args - Arguments to find a OAuthProvider
   * @example
   * // Get one OAuthProvider
   * const oAuthProvider = await prisma.oAuthProvider.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OAuthProviderFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OAuthProviderFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OAuthProviderClient<runtime.Types.Result.GetResult<Prisma.$OAuthProviderPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OAuthProviders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OAuthProviderFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OAuthProviders
   * const oAuthProviders = await prisma.oAuthProvider.findMany()
   * 
   * // Get first 10 OAuthProviders
   * const oAuthProviders = await prisma.oAuthProvider.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const oAuthProviderWithIdOnly = await prisma.oAuthProvider.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends OAuthProviderFindManyArgs>(args?: Prisma.SelectSubset<T, OAuthProviderFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OAuthProviderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OAuthProvider.
   * @param {OAuthProviderCreateArgs} args - Arguments to create a OAuthProvider.
   * @example
   * // Create one OAuthProvider
   * const OAuthProvider = await prisma.oAuthProvider.create({
   *   data: {
   *     // ... data to create a OAuthProvider
   *   }
   * })
   * 
   */
  create<T extends OAuthProviderCreateArgs>(args: Prisma.SelectSubset<T, OAuthProviderCreateArgs<ExtArgs>>): Prisma.Prisma__OAuthProviderClient<runtime.Types.Result.GetResult<Prisma.$OAuthProviderPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OAuthProviders.
   * @param {OAuthProviderCreateManyArgs} args - Arguments to create many OAuthProviders.
   * @example
   * // Create many OAuthProviders
   * const oAuthProvider = await prisma.oAuthProvider.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends OAuthProviderCreateManyArgs>(args?: Prisma.SelectSubset<T, OAuthProviderCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many OAuthProviders and returns the data saved in the database.
   * @param {OAuthProviderCreateManyAndReturnArgs} args - Arguments to create many OAuthProviders.
   * @example
   * // Create many OAuthProviders
   * const oAuthProvider = await prisma.oAuthProvider.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many OAuthProviders and only return the `id`
   * const oAuthProviderWithIdOnly = await prisma.oAuthProvider.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends OAuthProviderCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, OAuthProviderCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OAuthProviderPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a OAuthProvider.
   * @param {OAuthProviderDeleteArgs} args - Arguments to delete one OAuthProvider.
   * @example
   * // Delete one OAuthProvider
   * const OAuthProvider = await prisma.oAuthProvider.delete({
   *   where: {
   *     // ... filter to delete one OAuthProvider
   *   }
   * })
   * 
   */
  delete<T extends OAuthProviderDeleteArgs>(args: Prisma.SelectSubset<T, OAuthProviderDeleteArgs<ExtArgs>>): Prisma.Prisma__OAuthProviderClient<runtime.Types.Result.GetResult<Prisma.$OAuthProviderPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OAuthProvider.
   * @param {OAuthProviderUpdateArgs} args - Arguments to update one OAuthProvider.
   * @example
   * // Update one OAuthProvider
   * const oAuthProvider = await prisma.oAuthProvider.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends OAuthProviderUpdateArgs>(args: Prisma.SelectSubset<T, OAuthProviderUpdateArgs<ExtArgs>>): Prisma.Prisma__OAuthProviderClient<runtime.Types.Result.GetResult<Prisma.$OAuthProviderPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OAuthProviders.
   * @param {OAuthProviderDeleteManyArgs} args - Arguments to filter OAuthProviders to delete.
   * @example
   * // Delete a few OAuthProviders
   * const { count } = await prisma.oAuthProvider.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends OAuthProviderDeleteManyArgs>(args?: Prisma.SelectSubset<T, OAuthProviderDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OAuthProviders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OAuthProviderUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OAuthProviders
   * const oAuthProvider = await prisma.oAuthProvider.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends OAuthProviderUpdateManyArgs>(args: Prisma.SelectSubset<T, OAuthProviderUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OAuthProviders and returns the data updated in the database.
   * @param {OAuthProviderUpdateManyAndReturnArgs} args - Arguments to update many OAuthProviders.
   * @example
   * // Update many OAuthProviders
   * const oAuthProvider = await prisma.oAuthProvider.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more OAuthProviders and only return the `id`
   * const oAuthProviderWithIdOnly = await prisma.oAuthProvider.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends OAuthProviderUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, OAuthProviderUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OAuthProviderPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one OAuthProvider.
   * @param {OAuthProviderUpsertArgs} args - Arguments to update or create a OAuthProvider.
   * @example
   * // Update or create a OAuthProvider
   * const oAuthProvider = await prisma.oAuthProvider.upsert({
   *   create: {
   *     // ... data to create a OAuthProvider
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OAuthProvider we want to update
   *   }
   * })
   */
  upsert<T extends OAuthProviderUpsertArgs>(args: Prisma.SelectSubset<T, OAuthProviderUpsertArgs<ExtArgs>>): Prisma.Prisma__OAuthProviderClient<runtime.Types.Result.GetResult<Prisma.$OAuthProviderPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OAuthProviders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OAuthProviderCountArgs} args - Arguments to filter OAuthProviders to count.
   * @example
   * // Count the number of OAuthProviders
   * const count = await prisma.oAuthProvider.count({
   *   where: {
   *     // ... the filter for the OAuthProviders we want to count
   *   }
   * })
  **/
  count<T extends OAuthProviderCountArgs>(
    args?: Prisma.Subset<T, OAuthProviderCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OAuthProviderCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OAuthProvider.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OAuthProviderAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OAuthProviderAggregateArgs>(args: Prisma.Subset<T, OAuthProviderAggregateArgs>): Prisma.PrismaPromise<GetOAuthProviderAggregateType<T>>

  /**
   * Group by OAuthProvider.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OAuthProviderGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends OAuthProviderGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OAuthProviderGroupByArgs['orderBy'] }
      : { orderBy?: OAuthProviderGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OAuthProviderGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOAuthProviderGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the OAuthProvider model
 */
readonly fields: OAuthProviderFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OAuthProvider.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OAuthProviderClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the OAuthProvider model
 */
export interface OAuthProviderFieldRefs {
  readonly id: Prisma.FieldRef<"OAuthProvider", 'String'>
  readonly createdAt: Prisma.FieldRef<"OAuthProvider", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"OAuthProvider", 'DateTime'>
  readonly userId: Prisma.FieldRef<"OAuthProvider", 'String'>
  readonly provider: Prisma.FieldRef<"OAuthProvider", 'OAuthProviderType'>
  readonly username: Prisma.FieldRef<"OAuthProvider", 'String'>
  readonly accessToken: Prisma.FieldRef<"OAuthProvider", 'String'>
  readonly refreshToken: Prisma.FieldRef<"OAuthProvider", 'String'>
  readonly oauthId: Prisma.FieldRef<"OAuthProvider", 'String'>
}
    

// Custom InputTypes
/**
 * OAuthProvider findUnique
 */
export type OAuthProviderFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OAuthProvider
   */
  select?: Prisma.OAuthProviderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OAuthProvider
   */
  omit?: Prisma.OAuthProviderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OAuthProviderInclude<ExtArgs> | null
  /**
   * Filter, which OAuthProvider to fetch.
   */
  where: Prisma.OAuthProviderWhereUniqueInput
}

/**
 * OAuthProvider findUniqueOrThrow
 */
export type OAuthProviderFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OAuthProvider
   */
  select?: Prisma.OAuthProviderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OAuthProvider
   */
  omit?: Prisma.OAuthProviderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OAuthProviderInclude<ExtArgs> | null
  /**
   * Filter, which OAuthProvider to fetch.
   */
  where: Prisma.OAuthProviderWhereUniqueInput
}

/**
 * OAuthProvider findFirst
 */
export type OAuthProviderFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OAuthProvider
   */
  select?: Prisma.OAuthProviderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OAuthProvider
   */
  omit?: Prisma.OAuthProviderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OAuthProviderInclude<ExtArgs> | null
  /**
   * Filter, which OAuthProvider to fetch.
   */
  where?: Prisma.OAuthProviderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OAuthProviders to fetch.
   */
  orderBy?: Prisma.OAuthProviderOrderByWithRelationInput | Prisma.OAuthProviderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OAuthProviders.
   */
  cursor?: Prisma.OAuthProviderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OAuthProviders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OAuthProviders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OAuthProviders.
   */
  distinct?: Prisma.OAuthProviderScalarFieldEnum | Prisma.OAuthProviderScalarFieldEnum[]
}

/**
 * OAuthProvider findFirstOrThrow
 */
export type OAuthProviderFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OAuthProvider
   */
  select?: Prisma.OAuthProviderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OAuthProvider
   */
  omit?: Prisma.OAuthProviderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OAuthProviderInclude<ExtArgs> | null
  /**
   * Filter, which OAuthProvider to fetch.
   */
  where?: Prisma.OAuthProviderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OAuthProviders to fetch.
   */
  orderBy?: Prisma.OAuthProviderOrderByWithRelationInput | Prisma.OAuthProviderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OAuthProviders.
   */
  cursor?: Prisma.OAuthProviderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OAuthProviders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OAuthProviders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OAuthProviders.
   */
  distinct?: Prisma.OAuthProviderScalarFieldEnum | Prisma.OAuthProviderScalarFieldEnum[]
}

/**
 * OAuthProvider findMany
 */
export type OAuthProviderFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OAuthProvider
   */
  select?: Prisma.OAuthProviderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OAuthProvider
   */
  omit?: Prisma.OAuthProviderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OAuthProviderInclude<ExtArgs> | null
  /**
   * Filter, which OAuthProviders to fetch.
   */
  where?: Prisma.OAuthProviderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OAuthProviders to fetch.
   */
  orderBy?: Prisma.OAuthProviderOrderByWithRelationInput | Prisma.OAuthProviderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing OAuthProviders.
   */
  cursor?: Prisma.OAuthProviderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OAuthProviders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OAuthProviders.
   */
  skip?: number
  distinct?: Prisma.OAuthProviderScalarFieldEnum | Prisma.OAuthProviderScalarFieldEnum[]
}

/**
 * OAuthProvider create
 */
export type OAuthProviderCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OAuthProvider
   */
  select?: Prisma.OAuthProviderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OAuthProvider
   */
  omit?: Prisma.OAuthProviderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OAuthProviderInclude<ExtArgs> | null
  /**
   * The data needed to create a OAuthProvider.
   */
  data: Prisma.XOR<Prisma.OAuthProviderCreateInput, Prisma.OAuthProviderUncheckedCreateInput>
}

/**
 * OAuthProvider createMany
 */
export type OAuthProviderCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many OAuthProviders.
   */
  data: Prisma.OAuthProviderCreateManyInput | Prisma.OAuthProviderCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OAuthProvider createManyAndReturn
 */
export type OAuthProviderCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OAuthProvider
   */
  select?: Prisma.OAuthProviderSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OAuthProvider
   */
  omit?: Prisma.OAuthProviderOmit<ExtArgs> | null
  /**
   * The data used to create many OAuthProviders.
   */
  data: Prisma.OAuthProviderCreateManyInput | Prisma.OAuthProviderCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OAuthProviderIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * OAuthProvider update
 */
export type OAuthProviderUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OAuthProvider
   */
  select?: Prisma.OAuthProviderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OAuthProvider
   */
  omit?: Prisma.OAuthProviderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OAuthProviderInclude<ExtArgs> | null
  /**
   * The data needed to update a OAuthProvider.
   */
  data: Prisma.XOR<Prisma.OAuthProviderUpdateInput, Prisma.OAuthProviderUncheckedUpdateInput>
  /**
   * Choose, which OAuthProvider to update.
   */
  where: Prisma.OAuthProviderWhereUniqueInput
}

/**
 * OAuthProvider updateMany
 */
export type OAuthProviderUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update OAuthProviders.
   */
  data: Prisma.XOR<Prisma.OAuthProviderUpdateManyMutationInput, Prisma.OAuthProviderUncheckedUpdateManyInput>
  /**
   * Filter which OAuthProviders to update
   */
  where?: Prisma.OAuthProviderWhereInput
  /**
   * Limit how many OAuthProviders to update.
   */
  limit?: number
}

/**
 * OAuthProvider updateManyAndReturn
 */
export type OAuthProviderUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OAuthProvider
   */
  select?: Prisma.OAuthProviderSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OAuthProvider
   */
  omit?: Prisma.OAuthProviderOmit<ExtArgs> | null
  /**
   * The data used to update OAuthProviders.
   */
  data: Prisma.XOR<Prisma.OAuthProviderUpdateManyMutationInput, Prisma.OAuthProviderUncheckedUpdateManyInput>
  /**
   * Filter which OAuthProviders to update
   */
  where?: Prisma.OAuthProviderWhereInput
  /**
   * Limit how many OAuthProviders to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OAuthProviderIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * OAuthProvider upsert
 */
export type OAuthProviderUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OAuthProvider
   */
  select?: Prisma.OAuthProviderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OAuthProvider
   */
  omit?: Prisma.OAuthProviderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OAuthProviderInclude<ExtArgs> | null
  /**
   * The filter to search for the OAuthProvider to update in case it exists.
   */
  where: Prisma.OAuthProviderWhereUniqueInput
  /**
   * In case the OAuthProvider found by the `where` argument doesn't exist, create a new OAuthProvider with this data.
   */
  create: Prisma.XOR<Prisma.OAuthProviderCreateInput, Prisma.OAuthProviderUncheckedCreateInput>
  /**
   * In case the OAuthProvider was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OAuthProviderUpdateInput, Prisma.OAuthProviderUncheckedUpdateInput>
}

/**
 * OAuthProvider delete
 */
export type OAuthProviderDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OAuthProvider
   */
  select?: Prisma.OAuthProviderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OAuthProvider
   */
  omit?: Prisma.OAuthProviderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OAuthProviderInclude<ExtArgs> | null
  /**
   * Filter which OAuthProvider to delete.
   */
  where: Prisma.OAuthProviderWhereUniqueInput
}

/**
 * OAuthProvider deleteMany
 */
export type OAuthProviderDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OAuthProviders to delete
   */
  where?: Prisma.OAuthProviderWhereInput
  /**
   * Limit how many OAuthProviders to delete.
   */
  limit?: number
}

/**
 * OAuthProvider without action
 */
export type OAuthProviderDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OAuthProvider
   */
  select?: Prisma.OAuthProviderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OAuthProvider
   */
  omit?: Prisma.OAuthProviderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OAuthProviderInclude<ExtArgs> | null
}
