
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `UserPasskey` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model UserPasskey
 * 
 */
export type UserPasskeyModel = runtime.Types.Result.DefaultSelection<Prisma.$UserPasskeyPayload>

export type AggregateUserPasskey = {
  _count: UserPasskeyCountAggregateOutputType | null
  _min: UserPasskeyMinAggregateOutputType | null
  _max: UserPasskeyMaxAggregateOutputType | null
}

export type UserPasskeyMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  lastUsed: Date | null
  name: string | null
  userId: string | null
}

export type UserPasskeyMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  lastUsed: Date | null
  name: string | null
  userId: string | null
}

export type UserPasskeyCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  lastUsed: number
  name: number
  reg: number
  userId: number
  _all: number
}


export type UserPasskeyMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  lastUsed?: true
  name?: true
  userId?: true
}

export type UserPasskeyMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  lastUsed?: true
  name?: true
  userId?: true
}

export type UserPasskeyCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  lastUsed?: true
  name?: true
  reg?: true
  userId?: true
  _all?: true
}

export type UserPasskeyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserPasskey to aggregate.
   */
  where?: Prisma.UserPasskeyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserPasskeys to fetch.
   */
  orderBy?: Prisma.UserPasskeyOrderByWithRelationInput | Prisma.UserPasskeyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserPasskeyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserPasskeys from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserPasskeys.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserPasskeys
  **/
  _count?: true | UserPasskeyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserPasskeyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserPasskeyMaxAggregateInputType
}

export type GetUserPasskeyAggregateType<T extends UserPasskeyAggregateArgs> = {
      [P in keyof T & keyof AggregateUserPasskey]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserPasskey[P]>
    : Prisma.GetScalarType<T[P], AggregateUserPasskey[P]>
}




export type UserPasskeyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserPasskeyWhereInput
  orderBy?: Prisma.UserPasskeyOrderByWithAggregationInput | Prisma.UserPasskeyOrderByWithAggregationInput[]
  by: Prisma.UserPasskeyScalarFieldEnum[] | Prisma.UserPasskeyScalarFieldEnum
  having?: Prisma.UserPasskeyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserPasskeyCountAggregateInputType | true
  _min?: UserPasskeyMinAggregateInputType
  _max?: UserPasskeyMaxAggregateInputType
}

export type UserPasskeyGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  lastUsed: Date | null
  name: string
  reg: runtime.JsonValue
  userId: string
  _count: UserPasskeyCountAggregateOutputType | null
  _min: UserPasskeyMinAggregateOutputType | null
  _max: UserPasskeyMaxAggregateOutputType | null
}

type GetUserPasskeyGroupByPayload<T extends UserPasskeyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserPasskeyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserPasskeyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserPasskeyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserPasskeyGroupByOutputType[P]>
      }
    >
  >



export type UserPasskeyWhereInput = {
  AND?: Prisma.UserPasskeyWhereInput | Prisma.UserPasskeyWhereInput[]
  OR?: Prisma.UserPasskeyWhereInput[]
  NOT?: Prisma.UserPasskeyWhereInput | Prisma.UserPasskeyWhereInput[]
  id?: Prisma.StringFilter<"UserPasskey"> | string
  createdAt?: Prisma.DateTimeFilter<"UserPasskey"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UserPasskey"> | Date | string
  lastUsed?: Prisma.DateTimeNullableFilter<"UserPasskey"> | Date | string | null
  name?: Prisma.StringFilter<"UserPasskey"> | string
  reg?: Prisma.JsonFilter<"UserPasskey">
  userId?: Prisma.StringFilter<"UserPasskey"> | string
  User?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type UserPasskeyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  lastUsed?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  reg?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  User?: Prisma.UserOrderByWithRelationInput
}

export type UserPasskeyWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.UserPasskeyWhereInput | Prisma.UserPasskeyWhereInput[]
  OR?: Prisma.UserPasskeyWhereInput[]
  NOT?: Prisma.UserPasskeyWhereInput | Prisma.UserPasskeyWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"UserPasskey"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UserPasskey"> | Date | string
  lastUsed?: Prisma.DateTimeNullableFilter<"UserPasskey"> | Date | string | null
  name?: Prisma.StringFilter<"UserPasskey"> | string
  reg?: Prisma.JsonFilter<"UserPasskey">
  userId?: Prisma.StringFilter<"UserPasskey"> | string
  User?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type UserPasskeyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  lastUsed?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  reg?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  _count?: Prisma.UserPasskeyCountOrderByAggregateInput
  _max?: Prisma.UserPasskeyMaxOrderByAggregateInput
  _min?: Prisma.UserPasskeyMinOrderByAggregateInput
}

export type UserPasskeyScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserPasskeyScalarWhereWithAggregatesInput | Prisma.UserPasskeyScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserPasskeyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserPasskeyScalarWhereWithAggregatesInput | Prisma.UserPasskeyScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UserPasskey"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UserPasskey"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"UserPasskey"> | Date | string
  lastUsed?: Prisma.DateTimeNullableWithAggregatesFilter<"UserPasskey"> | Date | string | null
  name?: Prisma.StringWithAggregatesFilter<"UserPasskey"> | string
  reg?: Prisma.JsonWithAggregatesFilter<"UserPasskey">
  userId?: Prisma.StringWithAggregatesFilter<"UserPasskey"> | string
}

export type UserPasskeyCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  lastUsed?: Date | string | null
  name: string
  reg: Prisma.JsonNullValueInput | runtime.InputJsonValue
  User: Prisma.UserCreateNestedOneWithoutPasskeysInput
}

export type UserPasskeyUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  lastUsed?: Date | string | null
  name: string
  reg: Prisma.JsonNullValueInput | runtime.InputJsonValue
  userId: string
}

export type UserPasskeyUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastUsed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  reg?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  User?: Prisma.UserUpdateOneRequiredWithoutPasskeysNestedInput
}

export type UserPasskeyUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastUsed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  reg?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserPasskeyCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  lastUsed?: Date | string | null
  name: string
  reg: Prisma.JsonNullValueInput | runtime.InputJsonValue
  userId: string
}

export type UserPasskeyUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastUsed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  reg?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type UserPasskeyUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastUsed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  reg?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserPasskeyListRelationFilter = {
  every?: Prisma.UserPasskeyWhereInput
  some?: Prisma.UserPasskeyWhereInput
  none?: Prisma.UserPasskeyWhereInput
}

export type UserPasskeyOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserPasskeyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  lastUsed?: Prisma.SortOrder
  name?: Prisma.SortOrder
  reg?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type UserPasskeyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  lastUsed?: Prisma.SortOrder
  name?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type UserPasskeyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  lastUsed?: Prisma.SortOrder
  name?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type UserPasskeyCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserPasskeyCreateWithoutUserInput, Prisma.UserPasskeyUncheckedCreateWithoutUserInput> | Prisma.UserPasskeyCreateWithoutUserInput[] | Prisma.UserPasskeyUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserPasskeyCreateOrConnectWithoutUserInput | Prisma.UserPasskeyCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserPasskeyCreateManyUserInputEnvelope
  connect?: Prisma.UserPasskeyWhereUniqueInput | Prisma.UserPasskeyWhereUniqueInput[]
}

export type UserPasskeyUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserPasskeyCreateWithoutUserInput, Prisma.UserPasskeyUncheckedCreateWithoutUserInput> | Prisma.UserPasskeyCreateWithoutUserInput[] | Prisma.UserPasskeyUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserPasskeyCreateOrConnectWithoutUserInput | Prisma.UserPasskeyCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserPasskeyCreateManyUserInputEnvelope
  connect?: Prisma.UserPasskeyWhereUniqueInput | Prisma.UserPasskeyWhereUniqueInput[]
}

export type UserPasskeyUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserPasskeyCreateWithoutUserInput, Prisma.UserPasskeyUncheckedCreateWithoutUserInput> | Prisma.UserPasskeyCreateWithoutUserInput[] | Prisma.UserPasskeyUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserPasskeyCreateOrConnectWithoutUserInput | Prisma.UserPasskeyCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserPasskeyUpsertWithWhereUniqueWithoutUserInput | Prisma.UserPasskeyUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserPasskeyCreateManyUserInputEnvelope
  set?: Prisma.UserPasskeyWhereUniqueInput | Prisma.UserPasskeyWhereUniqueInput[]
  disconnect?: Prisma.UserPasskeyWhereUniqueInput | Prisma.UserPasskeyWhereUniqueInput[]
  delete?: Prisma.UserPasskeyWhereUniqueInput | Prisma.UserPasskeyWhereUniqueInput[]
  connect?: Prisma.UserPasskeyWhereUniqueInput | Prisma.UserPasskeyWhereUniqueInput[]
  update?: Prisma.UserPasskeyUpdateWithWhereUniqueWithoutUserInput | Prisma.UserPasskeyUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserPasskeyUpdateManyWithWhereWithoutUserInput | Prisma.UserPasskeyUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserPasskeyScalarWhereInput | Prisma.UserPasskeyScalarWhereInput[]
}

export type UserPasskeyUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserPasskeyCreateWithoutUserInput, Prisma.UserPasskeyUncheckedCreateWithoutUserInput> | Prisma.UserPasskeyCreateWithoutUserInput[] | Prisma.UserPasskeyUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserPasskeyCreateOrConnectWithoutUserInput | Prisma.UserPasskeyCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserPasskeyUpsertWithWhereUniqueWithoutUserInput | Prisma.UserPasskeyUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserPasskeyCreateManyUserInputEnvelope
  set?: Prisma.UserPasskeyWhereUniqueInput | Prisma.UserPasskeyWhereUniqueInput[]
  disconnect?: Prisma.UserPasskeyWhereUniqueInput | Prisma.UserPasskeyWhereUniqueInput[]
  delete?: Prisma.UserPasskeyWhereUniqueInput | Prisma.UserPasskeyWhereUniqueInput[]
  connect?: Prisma.UserPasskeyWhereUniqueInput | Prisma.UserPasskeyWhereUniqueInput[]
  update?: Prisma.UserPasskeyUpdateWithWhereUniqueWithoutUserInput | Prisma.UserPasskeyUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserPasskeyUpdateManyWithWhereWithoutUserInput | Prisma.UserPasskeyUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserPasskeyScalarWhereInput | Prisma.UserPasskeyScalarWhereInput[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type UserPasskeyCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  lastUsed?: Date | string | null
  name: string
  reg: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type UserPasskeyUncheckedCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  lastUsed?: Date | string | null
  name: string
  reg: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type UserPasskeyCreateOrConnectWithoutUserInput = {
  where: Prisma.UserPasskeyWhereUniqueInput
  create: Prisma.XOR<Prisma.UserPasskeyCreateWithoutUserInput, Prisma.UserPasskeyUncheckedCreateWithoutUserInput>
}

export type UserPasskeyCreateManyUserInputEnvelope = {
  data: Prisma.UserPasskeyCreateManyUserInput | Prisma.UserPasskeyCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserPasskeyUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserPasskeyWhereUniqueInput
  update: Prisma.XOR<Prisma.UserPasskeyUpdateWithoutUserInput, Prisma.UserPasskeyUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserPasskeyCreateWithoutUserInput, Prisma.UserPasskeyUncheckedCreateWithoutUserInput>
}

export type UserPasskeyUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserPasskeyWhereUniqueInput
  data: Prisma.XOR<Prisma.UserPasskeyUpdateWithoutUserInput, Prisma.UserPasskeyUncheckedUpdateWithoutUserInput>
}

export type UserPasskeyUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserPasskeyScalarWhereInput
  data: Prisma.XOR<Prisma.UserPasskeyUpdateManyMutationInput, Prisma.UserPasskeyUncheckedUpdateManyWithoutUserInput>
}

export type UserPasskeyScalarWhereInput = {
  AND?: Prisma.UserPasskeyScalarWhereInput | Prisma.UserPasskeyScalarWhereInput[]
  OR?: Prisma.UserPasskeyScalarWhereInput[]
  NOT?: Prisma.UserPasskeyScalarWhereInput | Prisma.UserPasskeyScalarWhereInput[]
  id?: Prisma.StringFilter<"UserPasskey"> | string
  createdAt?: Prisma.DateTimeFilter<"UserPasskey"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UserPasskey"> | Date | string
  lastUsed?: Prisma.DateTimeNullableFilter<"UserPasskey"> | Date | string | null
  name?: Prisma.StringFilter<"UserPasskey"> | string
  reg?: Prisma.JsonFilter<"UserPasskey">
  userId?: Prisma.StringFilter<"UserPasskey"> | string
}

export type UserPasskeyCreateManyUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  lastUsed?: Date | string | null
  name: string
  reg: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type UserPasskeyUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastUsed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  reg?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type UserPasskeyUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastUsed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  reg?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type UserPasskeyUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastUsed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  reg?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}



export type UserPasskeySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  lastUsed?: boolean
  name?: boolean
  reg?: boolean
  userId?: boolean
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userPasskey"]>

export type UserPasskeySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  lastUsed?: boolean
  name?: boolean
  reg?: boolean
  userId?: boolean
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userPasskey"]>

export type UserPasskeySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  lastUsed?: boolean
  name?: boolean
  reg?: boolean
  userId?: boolean
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userPasskey"]>

export type UserPasskeySelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  lastUsed?: boolean
  name?: boolean
  reg?: boolean
  userId?: boolean
}

export type UserPasskeyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "lastUsed" | "name" | "reg" | "userId", ExtArgs["result"]["userPasskey"]>
export type UserPasskeyInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserPasskeyIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserPasskeyIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $UserPasskeyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserPasskey"
  objects: {
    User: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    lastUsed: Date | null
    name: string
    reg: runtime.JsonValue
    userId: string
  }, ExtArgs["result"]["userPasskey"]>
  composites: {}
}

export type UserPasskeyGetPayload<S extends boolean | null | undefined | UserPasskeyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserPasskeyPayload, S>

export type UserPasskeyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserPasskeyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserPasskeyCountAggregateInputType | true
  }

export interface UserPasskeyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserPasskey'], meta: { name: 'UserPasskey' } }
  /**
   * Find zero or one UserPasskey that matches the filter.
   * @param {UserPasskeyFindUniqueArgs} args - Arguments to find a UserPasskey
   * @example
   * // Get one UserPasskey
   * const userPasskey = await prisma.userPasskey.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserPasskeyFindUniqueArgs>(args: Prisma.SelectSubset<T, UserPasskeyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserPasskeyClient<runtime.Types.Result.GetResult<Prisma.$UserPasskeyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserPasskey that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserPasskeyFindUniqueOrThrowArgs} args - Arguments to find a UserPasskey
   * @example
   * // Get one UserPasskey
   * const userPasskey = await prisma.userPasskey.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserPasskeyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserPasskeyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserPasskeyClient<runtime.Types.Result.GetResult<Prisma.$UserPasskeyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserPasskey that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPasskeyFindFirstArgs} args - Arguments to find a UserPasskey
   * @example
   * // Get one UserPasskey
   * const userPasskey = await prisma.userPasskey.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserPasskeyFindFirstArgs>(args?: Prisma.SelectSubset<T, UserPasskeyFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserPasskeyClient<runtime.Types.Result.GetResult<Prisma.$UserPasskeyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserPasskey that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPasskeyFindFirstOrThrowArgs} args - Arguments to find a UserPasskey
   * @example
   * // Get one UserPasskey
   * const userPasskey = await prisma.userPasskey.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserPasskeyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserPasskeyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserPasskeyClient<runtime.Types.Result.GetResult<Prisma.$UserPasskeyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserPasskeys that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPasskeyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserPasskeys
   * const userPasskeys = await prisma.userPasskey.findMany()
   * 
   * // Get first 10 UserPasskeys
   * const userPasskeys = await prisma.userPasskey.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userPasskeyWithIdOnly = await prisma.userPasskey.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserPasskeyFindManyArgs>(args?: Prisma.SelectSubset<T, UserPasskeyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPasskeyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserPasskey.
   * @param {UserPasskeyCreateArgs} args - Arguments to create a UserPasskey.
   * @example
   * // Create one UserPasskey
   * const UserPasskey = await prisma.userPasskey.create({
   *   data: {
   *     // ... data to create a UserPasskey
   *   }
   * })
   * 
   */
  create<T extends UserPasskeyCreateArgs>(args: Prisma.SelectSubset<T, UserPasskeyCreateArgs<ExtArgs>>): Prisma.Prisma__UserPasskeyClient<runtime.Types.Result.GetResult<Prisma.$UserPasskeyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserPasskeys.
   * @param {UserPasskeyCreateManyArgs} args - Arguments to create many UserPasskeys.
   * @example
   * // Create many UserPasskeys
   * const userPasskey = await prisma.userPasskey.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserPasskeyCreateManyArgs>(args?: Prisma.SelectSubset<T, UserPasskeyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserPasskeys and returns the data saved in the database.
   * @param {UserPasskeyCreateManyAndReturnArgs} args - Arguments to create many UserPasskeys.
   * @example
   * // Create many UserPasskeys
   * const userPasskey = await prisma.userPasskey.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserPasskeys and only return the `id`
   * const userPasskeyWithIdOnly = await prisma.userPasskey.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserPasskeyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserPasskeyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPasskeyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserPasskey.
   * @param {UserPasskeyDeleteArgs} args - Arguments to delete one UserPasskey.
   * @example
   * // Delete one UserPasskey
   * const UserPasskey = await prisma.userPasskey.delete({
   *   where: {
   *     // ... filter to delete one UserPasskey
   *   }
   * })
   * 
   */
  delete<T extends UserPasskeyDeleteArgs>(args: Prisma.SelectSubset<T, UserPasskeyDeleteArgs<ExtArgs>>): Prisma.Prisma__UserPasskeyClient<runtime.Types.Result.GetResult<Prisma.$UserPasskeyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserPasskey.
   * @param {UserPasskeyUpdateArgs} args - Arguments to update one UserPasskey.
   * @example
   * // Update one UserPasskey
   * const userPasskey = await prisma.userPasskey.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserPasskeyUpdateArgs>(args: Prisma.SelectSubset<T, UserPasskeyUpdateArgs<ExtArgs>>): Prisma.Prisma__UserPasskeyClient<runtime.Types.Result.GetResult<Prisma.$UserPasskeyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserPasskeys.
   * @param {UserPasskeyDeleteManyArgs} args - Arguments to filter UserPasskeys to delete.
   * @example
   * // Delete a few UserPasskeys
   * const { count } = await prisma.userPasskey.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserPasskeyDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserPasskeyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserPasskeys.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPasskeyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserPasskeys
   * const userPasskey = await prisma.userPasskey.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserPasskeyUpdateManyArgs>(args: Prisma.SelectSubset<T, UserPasskeyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserPasskeys and returns the data updated in the database.
   * @param {UserPasskeyUpdateManyAndReturnArgs} args - Arguments to update many UserPasskeys.
   * @example
   * // Update many UserPasskeys
   * const userPasskey = await prisma.userPasskey.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserPasskeys and only return the `id`
   * const userPasskeyWithIdOnly = await prisma.userPasskey.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserPasskeyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserPasskeyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPasskeyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserPasskey.
   * @param {UserPasskeyUpsertArgs} args - Arguments to update or create a UserPasskey.
   * @example
   * // Update or create a UserPasskey
   * const userPasskey = await prisma.userPasskey.upsert({
   *   create: {
   *     // ... data to create a UserPasskey
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserPasskey we want to update
   *   }
   * })
   */
  upsert<T extends UserPasskeyUpsertArgs>(args: Prisma.SelectSubset<T, UserPasskeyUpsertArgs<ExtArgs>>): Prisma.Prisma__UserPasskeyClient<runtime.Types.Result.GetResult<Prisma.$UserPasskeyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserPasskeys.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPasskeyCountArgs} args - Arguments to filter UserPasskeys to count.
   * @example
   * // Count the number of UserPasskeys
   * const count = await prisma.userPasskey.count({
   *   where: {
   *     // ... the filter for the UserPasskeys we want to count
   *   }
   * })
  **/
  count<T extends UserPasskeyCountArgs>(
    args?: Prisma.Subset<T, UserPasskeyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserPasskeyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserPasskey.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPasskeyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserPasskeyAggregateArgs>(args: Prisma.Subset<T, UserPasskeyAggregateArgs>): Prisma.PrismaPromise<GetUserPasskeyAggregateType<T>>

  /**
   * Group by UserPasskey.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPasskeyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserPasskeyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserPasskeyGroupByArgs['orderBy'] }
      : { orderBy?: UserPasskeyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserPasskeyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserPasskeyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserPasskey model
 */
readonly fields: UserPasskeyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserPasskey.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserPasskeyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  User<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserPasskey model
 */
export interface UserPasskeyFieldRefs {
  readonly id: Prisma.FieldRef<"UserPasskey", 'String'>
  readonly createdAt: Prisma.FieldRef<"UserPasskey", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"UserPasskey", 'DateTime'>
  readonly lastUsed: Prisma.FieldRef<"UserPasskey", 'DateTime'>
  readonly name: Prisma.FieldRef<"UserPasskey", 'String'>
  readonly reg: Prisma.FieldRef<"UserPasskey", 'Json'>
  readonly userId: Prisma.FieldRef<"UserPasskey", 'String'>
}
    

// Custom InputTypes
/**
 * UserPasskey findUnique
 */
export type UserPasskeyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPasskey
   */
  select?: Prisma.UserPasskeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPasskey
   */
  omit?: Prisma.UserPasskeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPasskeyInclude<ExtArgs> | null
  /**
   * Filter, which UserPasskey to fetch.
   */
  where: Prisma.UserPasskeyWhereUniqueInput
}

/**
 * UserPasskey findUniqueOrThrow
 */
export type UserPasskeyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPasskey
   */
  select?: Prisma.UserPasskeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPasskey
   */
  omit?: Prisma.UserPasskeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPasskeyInclude<ExtArgs> | null
  /**
   * Filter, which UserPasskey to fetch.
   */
  where: Prisma.UserPasskeyWhereUniqueInput
}

/**
 * UserPasskey findFirst
 */
export type UserPasskeyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPasskey
   */
  select?: Prisma.UserPasskeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPasskey
   */
  omit?: Prisma.UserPasskeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPasskeyInclude<ExtArgs> | null
  /**
   * Filter, which UserPasskey to fetch.
   */
  where?: Prisma.UserPasskeyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserPasskeys to fetch.
   */
  orderBy?: Prisma.UserPasskeyOrderByWithRelationInput | Prisma.UserPasskeyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserPasskeys.
   */
  cursor?: Prisma.UserPasskeyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserPasskeys from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserPasskeys.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserPasskeys.
   */
  distinct?: Prisma.UserPasskeyScalarFieldEnum | Prisma.UserPasskeyScalarFieldEnum[]
}

/**
 * UserPasskey findFirstOrThrow
 */
export type UserPasskeyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPasskey
   */
  select?: Prisma.UserPasskeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPasskey
   */
  omit?: Prisma.UserPasskeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPasskeyInclude<ExtArgs> | null
  /**
   * Filter, which UserPasskey to fetch.
   */
  where?: Prisma.UserPasskeyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserPasskeys to fetch.
   */
  orderBy?: Prisma.UserPasskeyOrderByWithRelationInput | Prisma.UserPasskeyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserPasskeys.
   */
  cursor?: Prisma.UserPasskeyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserPasskeys from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserPasskeys.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserPasskeys.
   */
  distinct?: Prisma.UserPasskeyScalarFieldEnum | Prisma.UserPasskeyScalarFieldEnum[]
}

/**
 * UserPasskey findMany
 */
export type UserPasskeyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPasskey
   */
  select?: Prisma.UserPasskeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPasskey
   */
  omit?: Prisma.UserPasskeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPasskeyInclude<ExtArgs> | null
  /**
   * Filter, which UserPasskeys to fetch.
   */
  where?: Prisma.UserPasskeyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserPasskeys to fetch.
   */
  orderBy?: Prisma.UserPasskeyOrderByWithRelationInput | Prisma.UserPasskeyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserPasskeys.
   */
  cursor?: Prisma.UserPasskeyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserPasskeys from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserPasskeys.
   */
  skip?: number
  distinct?: Prisma.UserPasskeyScalarFieldEnum | Prisma.UserPasskeyScalarFieldEnum[]
}

/**
 * UserPasskey create
 */
export type UserPasskeyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPasskey
   */
  select?: Prisma.UserPasskeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPasskey
   */
  omit?: Prisma.UserPasskeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPasskeyInclude<ExtArgs> | null
  /**
   * The data needed to create a UserPasskey.
   */
  data: Prisma.XOR<Prisma.UserPasskeyCreateInput, Prisma.UserPasskeyUncheckedCreateInput>
}

/**
 * UserPasskey createMany
 */
export type UserPasskeyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserPasskeys.
   */
  data: Prisma.UserPasskeyCreateManyInput | Prisma.UserPasskeyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserPasskey createManyAndReturn
 */
export type UserPasskeyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPasskey
   */
  select?: Prisma.UserPasskeySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserPasskey
   */
  omit?: Prisma.UserPasskeyOmit<ExtArgs> | null
  /**
   * The data used to create many UserPasskeys.
   */
  data: Prisma.UserPasskeyCreateManyInput | Prisma.UserPasskeyCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPasskeyIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserPasskey update
 */
export type UserPasskeyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPasskey
   */
  select?: Prisma.UserPasskeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPasskey
   */
  omit?: Prisma.UserPasskeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPasskeyInclude<ExtArgs> | null
  /**
   * The data needed to update a UserPasskey.
   */
  data: Prisma.XOR<Prisma.UserPasskeyUpdateInput, Prisma.UserPasskeyUncheckedUpdateInput>
  /**
   * Choose, which UserPasskey to update.
   */
  where: Prisma.UserPasskeyWhereUniqueInput
}

/**
 * UserPasskey updateMany
 */
export type UserPasskeyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserPasskeys.
   */
  data: Prisma.XOR<Prisma.UserPasskeyUpdateManyMutationInput, Prisma.UserPasskeyUncheckedUpdateManyInput>
  /**
   * Filter which UserPasskeys to update
   */
  where?: Prisma.UserPasskeyWhereInput
  /**
   * Limit how many UserPasskeys to update.
   */
  limit?: number
}

/**
 * UserPasskey updateManyAndReturn
 */
export type UserPasskeyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPasskey
   */
  select?: Prisma.UserPasskeySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserPasskey
   */
  omit?: Prisma.UserPasskeyOmit<ExtArgs> | null
  /**
   * The data used to update UserPasskeys.
   */
  data: Prisma.XOR<Prisma.UserPasskeyUpdateManyMutationInput, Prisma.UserPasskeyUncheckedUpdateManyInput>
  /**
   * Filter which UserPasskeys to update
   */
  where?: Prisma.UserPasskeyWhereInput
  /**
   * Limit how many UserPasskeys to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPasskeyIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserPasskey upsert
 */
export type UserPasskeyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPasskey
   */
  select?: Prisma.UserPasskeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPasskey
   */
  omit?: Prisma.UserPasskeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPasskeyInclude<ExtArgs> | null
  /**
   * The filter to search for the UserPasskey to update in case it exists.
   */
  where: Prisma.UserPasskeyWhereUniqueInput
  /**
   * In case the UserPasskey found by the `where` argument doesn't exist, create a new UserPasskey with this data.
   */
  create: Prisma.XOR<Prisma.UserPasskeyCreateInput, Prisma.UserPasskeyUncheckedCreateInput>
  /**
   * In case the UserPasskey was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserPasskeyUpdateInput, Prisma.UserPasskeyUncheckedUpdateInput>
}

/**
 * UserPasskey delete
 */
export type UserPasskeyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPasskey
   */
  select?: Prisma.UserPasskeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPasskey
   */
  omit?: Prisma.UserPasskeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPasskeyInclude<ExtArgs> | null
  /**
   * Filter which UserPasskey to delete.
   */
  where: Prisma.UserPasskeyWhereUniqueInput
}

/**
 * UserPasskey deleteMany
 */
export type UserPasskeyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserPasskeys to delete
   */
  where?: Prisma.UserPasskeyWhereInput
  /**
   * Limit how many UserPasskeys to delete.
   */
  limit?: number
}

/**
 * UserPasskey without action
 */
export type UserPasskeyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPasskey
   */
  select?: Prisma.UserPasskeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPasskey
   */
  omit?: Prisma.UserPasskeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPasskeyInclude<ExtArgs> | null
}
